### ISSUE TITLE
Properties userGroup und directUserGroup 

### ISSUE THREAD

**Issue by MichelleBindel** [hitontology/ontology#101]
Aktuell führen in der Ontologie beide von SoftwareProduct zu UserGroupClassified. 

https://hitontology.eu/ontology/userGroup
https://hitontology.eu/ontology/directUserGroup

Eigentlich sollte (dem Schema folgend) userGroup von SoftwareProduct zu UserGroupCitation gehen.

**Comment by KonradHoeffner** [comment]
Ja, userGroup muss zu UserGroupCitation und userGroupDirect zu UserGroupClassified.
Analog gillt das für alle x / xDirect - Paare.

**Comment by MichelleBindel** [comment]
@KonradHoeffner Passt du das in der Ontolgie an?

**Comment by KonradHoeffner** [comment]
Done. Übrigens Issue #101 überschritten, Glückwunsch :-)
