### ISSUE TITLE
manuell Kataloge verknüpfen

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#102]
Da LIMES nicht erfolgreich war, siehe #94, bitte manuell probieren. Für die Functions und Application Systems hat @FranziskaJahn das schon getan.
Die Links liegen im Ordner <https://drive.google.com/drive/folders/1fVpLvz6FnleQxJdmNeOCpczmlMM1-k_t>.

## Verknüpfen
@MichelleBindel 
- [x] Feature
- [x] Function
- [x] Application System

## Kontrollieren
@FranziskaJahn  
- [x] Feature
- [x] Function
- [x] Application System

## Einbauen
@KonradHoeffner 
- [x] Feature
- [x] Function
- [x] Application System

**Comment by KonradHoeffner** [comment]
@FranziskaJahn bitte Features prüfen.

**Comment by KonradHoeffner** [comment]
Da sind gar keine Featurelinks drin, erst mal gucken ob wir welche finden.

**Comment by KonradHoeffner** [comment]
Die Links sind noch da, @MichelleBindel sucht sie heraus und gibt sie uns. Update: Michelle hat die Daten gefunden und in die Tabelle kopiert.

**Comment by FranziskaJahn** [comment]
Ich baue noch SKOS-Relationen ein.

**Comment by FranziskaJahn** [comment]
- [x] Features
- [x] Functions
- [x] Application systems

Siehe Ordner oben, da liegen alle Tabellen.
