### ISSUE TITLE
Renaming relationships

### ISSUE THREAD

**Issue by FranziskaJahn** [hitontology/ontology#109]
Rename

- "evaluates application system used in" to "evaluates application system or software product used in"
- "evaluates application system used by" to "evaluates application system or software product used by"

**Comment by KonradHoeffner** [comment]
Those relationships are:

1. [hito:evaluatesApplicationSystemTypeUsedInUnit](https://hitontology.eu/ontology/evaluatesApplicationSystemTypeUsedInUnit), current label "evaluates", domain hito:Study, range hito:OrganizationalUnitCitation
2. [hito:evaluatesApplicationSystemTypeHavingUserGroup](https://hitontology.eu/ontology/evaluatesApplicationSystemTypeHavingUserGroup), current label "evaluates", domain hito:Study, range hito:UserGroupCitation

I interpret the task to mean:

1. change the label of 1. from "evaluates" to "evaluates application system or software product used in"
2. change the label of 2. from "evaluates" to "evaluates application system or software product used by"

This is very easy to do and will not break anything technically, however it will increases the label length dramatically and may have unintended consequences on displays in our tools.

Shall I continue and implement that?
