### ISSUE TITLE
rename outcome criteria in ontology

### ISSUE THREAD

**Issue by FranziskaJahn** [hitontology/ontology#110]
Outcome criteria muss zu outcome criterion werden - sonst haben wir auch nirgendwo die Mehrzahl.

**Comment by KonradHoeffner** [comment]
@KonradHoeffner: Rename in ontology.
@FranziskaJahn : Rename in diagram.

**Comment by KonradHoeffner** [comment]
Laut Merriam-Webster ist Criteria als Singularform auch üblich: <https://www.merriam-webster.com/words-at-play/criteria-vs-criterion-singular-plural-grammar>.

> Criteria is typically a plural noun referring to standards on which a judgment can be made. Its singular is criterion, but evidence shows that criteria is frequently being used as a singular as well as a plural, much like data and agenda and their lesser-used singulars datum and agendum.

Wollen wir das trotzdem umbenennen? Es wohl kein so großer Aufwand wie letztens die großangelegte Umbenennung, die sich tagelang durch sämtliche Services zog, da OutcomeCritieria wohl nicht in der Datenbank und den zugehörigen Tools genutzt wird, also wie du möchtest.

**Comment by KonradHoeffner** [comment]
Nach Rücksprache lassen wir es so wie es ist.
