### ISSUE TITLE
classifieds without catalogue

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#29]
There are classifieds without a catalogue. Is that something we want to support or should I create new catalogues for them?

```
PREFIX : <http://hitontology.eu/ontology/>
SELECT DISTINCT(?c)
{
 {?c a :OrganizationalUnitClassified} UNION
 {?c a :EnterpriseFunctionClassified} UNION
 {?c a :FeatureClassified} UNION
 {?c a :ApplicationSystemClassified} UNION
 {?c a :UserGroupClassified}

 MINUS {?c ?p [a [rdfs:subClassOf :Catalogue]].}
}
```

instance
--
http://hitontology.eu/ontology/Accident_and_Emergency_department_environment
http://hitontology.eu/ontology/Cardiology_department_environment
http://hitontology.eu/ontology/Care_of_the_elderly_department_environment
http://hitontology.eu/ontology/Dermatology_department_environment
http://hitontology.eu/ontology/Endocrinology_department_environment
http://hitontology.eu/ontology/Gastroenterology_department_environment
http://hitontology.eu/ontology/General_medical_department_environment
http://hitontology.eu/ontology/Gynecology_department_environment
http://hitontology.eu/ontology/Hospital_environment
http://hitontology.eu/ontology/Infectious_diseases_department_environment
http://hitontology.eu/ontology/Intensive_care_unit_environment
http://hitontology.eu/ontology/Laboratory_environment
http://hitontology.eu/ontology/Neonatal_intensive_care_unit_environment
http://hitontology.eu/ontology/Nephrology_department_environment
http://hitontology.eu/ontology/Orthopedic_department_environment
http://hitontology.eu/ontology/Pediatric_department_environment
http://hitontology.eu/ontology/Pediatric_intensive_care_unit_environment
http://hitontology.eu/ontology/Psychiatry_department_environment
http://hitontology.eu/ontology/Radiology_department_environment
http://hitontology.eu/ontology/Rheumatology_department_environment
http://hitontology.eu/ontology/Surgical_department_environment
http://hitontology.eu/ontology/Genetics_department_environment
http://hitontology.eu/ontology/Medical_center_environment
http://hitontology.eu/ontology/Audit
http://hitontology.eu/ontology/ManageAdministrativeTransactionProcessing
http://hitontology.eu/ontology/ManageCareCoordinationAndReporting
http://hitontology.eu/ontology/ManageClinicalDocumentation
http://hitontology.eu/ontology/ManageClinicalHistory
http://hitontology.eu/ontology/ManageClinicalWorkflowTasking
http://hitontology.eu/ontology/ManageCommunication
http://hitontology.eu/ontology/ManageHealthcareResourceAvailabilityInformation
http://hitontology.eu/ontology/ManageHealthcareResourceScheduling
http://hitontology.eu/ontology/ManageMedicationAdministration
http://hitontology.eu/ontology/ManageMedicationImmunizationAndTreatmentAdministration
http://hitontology.eu/ontology/ManageMedicationOrders
http://hitontology.eu/ontology/ManageNonMedicationPatientCareOrders
http://hitontology.eu/ontology/ManageOrderSetTemplates
http://hitontology.eu/ontology/ManageOrders
http://hitontology.eu/ontology/ManageOrdersForDiagnositcScreeningTests
http://hitontology.eu/ontology/ManageOrdersForReferral
http://hitontology.eu/ontology/ManagePatientHistory
http://hitontology.eu/ontology/ManageProblemList
http://hitontology.eu/ontology/ManageRecordEntryAmendedCorrectedAndAugmentedState
http://hitontology.eu/ontology/ManageResourceAvailability
http://hitontology.eu/ontology/ManageResults
http://hitontology.eu/ontology/ManageResultsOfDiagnosticTests
http://hitontology.eu/ontology/MeasurementAnalysisResearchAndReports
http://hitontology.eu/ontology/MedicationAlertOverrides
http://hitontology.eu/ontology/MedicationAndAllergyInteractionChecking
http://hitontology.eu/ontology/MedicationOrderEfficiencies
http://hitontology.eu/ontology/ProduceASummaryRecordOfCare
http://hitontology.eu/ontology/RegistryAndDirectoryServices
http://hitontology.eu/ontology/StandardTerminologyAndTerminologyServices
http://hitontology.eu/ontology/SupportCareCoordinationAndReporting
http://hitontology.eu/ontology/SupportClinicalDocumentation
http://hitontology.eu/ontology/SupportForCommunicationBetweenOrganizations
http://hitontology.eu/ontology/SupportForContextSensitiveCarePlansGuidelinesProtocols
http://hitontology.eu/ontology/SupportForMedicationAdministration
http://hitontology.eu/ontology/SupportForMedicationInteractionAndAllergyChecking
http://hitontology.eu/ontology/SupportForMedicationOrderingEfficiencies
http://hitontology.eu/ontology/SupportForMedicationRecommendations
http://hitontology.eu/ontology/SupportForPatientContextDrivenAssessments
http://hitontology.eu/ontology/SupportForStandardAssessments
http://hitontology.eu/ontology/SupportOfPatientSpecificDosingAndWarnings
http://hitontology.eu/ontology/SupportOrders
http://hitontology.eu/ontology/SupportOrdersForDiagnosticScreeningTests
http://hitontology.eu/ontology/SupportRemoteHealthcareServices
http://hitontology.eu/ontology/SupportTriageCategorization
http://hitontology.eu/ontology/SupportforStandardCarePlansGuidelinesProtocols
http://hitontology.eu/ontology/UseOrderSets
http://hitontology.eu/ontology/Decision_Support_System
http://hitontology.eu/ontology/Electronic_Patient_Record_System
http://hitontology.eu/ontology/Enterprise_Resource_Planning_System
http://hitontology.eu/ontology/Laboratory_Information_System
http://hitontology.eu/ontology/Medical_Documentation_System
http://hitontology.eu/ontology/Nursing_Management_and_Documentation_System
http://hitontology.eu/ontology/Operation_Management_System
http://hitontology.eu/ontology/Outpatient_Management_System
http://hitontology.eu/ontology/Patient_Administration_System
http://hitontology.eu/ontology/Patient_Data_Management_System_PDMS
http://hitontology.eu/ontology/Picture_Archiving_and_Communication_System_PACS
http://hitontology.eu/ontology/Provider_or_Physician_Order_Entry_System_POE
http://hitontology.eu/ontology/Radiology_Information_System
http://hitontology.eu/ontology/Teleradiology_system
http://hitontology.eu/ontology/Administrative_healthcare_staff_occupation
http://hitontology.eu/ontology/Clerical_occupation_occupation
http://hitontology.eu/ontology/Clerk_occupation
http://hitontology.eu/ontology/Laboratory_technician_occupation
http://hitontology.eu/ontology/Medical_technician_occupation
http://hitontology.eu/ontology/Pharmacist_occupation
http://hitontology.eu/ontology/Physician_occupation
http://hitontology.eu/ontology/Professional_nurse_occupation
http://hitontology.eu/ontology/Radiologist_occupation
http://hitontology.eu/ontology/Surgeon_occupation
http://hitontology.eu/ontology/Woman_person

**Comment by KonradHoeffner** [comment]
Von @vdornauer:

> Diese Beispiele stammen aus jeden Fall alle aus SNOMED CT. Kannst du mir die Einträge schicken, dann checke ich ob die alle aus SNOMED CT sind, was sie glaube ich sein müssten.
> 
> SNOMED CT ist für Organizational Unit und User Group verwendet worden, wobei wir bei User Group nochmal diskutieren sollten, ob wir hier nicht den Einteilungskatalog von HITCOMP nehmen, sollte es einen dort geben.

**Comment by KonradHoeffner** [comment]
Refactored SNOMED CT user groups and organizational units into a new file snomed.ttl.

**Comment by VerenaDornauer** [comment]
Thanks Konrad!

**Comment by KonradHoeffner** [comment]
There are still some classifieds that don't have a catalogue:

classified
--
http://hitontology.eu/ontology/ElectronicPatientRecordSystem
http://hitontology.eu/ontology/PatientDataManagementSystemPDMS
http://hitontology.eu/ontology/PictureArchivingAndCommunicationSystemPACS
http://hitontology.eu/ontology/ProviderOrPhysicianOrderEntrySystemPOE
http://hitontology.eu/ontology/DecisionSupportSystem
http://hitontology.eu/ontology/EnterpriseResourcePlanningSystem
http://hitontology.eu/ontology/LaboratoryInformationSystem
http://hitontology.eu/ontology/MedicalDocumentationSystem
http://hitontology.eu/ontology/NursingManagementAndDocumentationSystem
http://hitontology.eu/ontology/OperationManagementSystem
http://hitontology.eu/ontology/OutpatientManagementSystem
http://hitontology.eu/ontology/PatientAdministrationSystem
http://hitontology.eu/ontology/RadiologyInformationSystem
http://hitontology.eu/ontology/TeleradiologySystem

**Comment by KonradHoeffner** [comment]
The classifieds above are all application systems that have the blue book as a source given as a string, so they belong to the blue book application system catalogue https://hitontology.eu/ontology/BbApplicationSystemCatalogue. However, in the BB catalogue, the classified suffixes are prefixed with "Bb".

**Comment by KonradHoeffner** [comment]
All the classifieds are defined in hito.ttl and used in the following spots:

```
hito.ttl:880:                                              :applicationSystemClassified :OutpatientManagementSystem ;
hito.ttl:888:                                                               :applicationSystemClassified :OutpatientManagementSystem ;
hito.ttl:1927:      :applicationSystemClassified :PatientDataManagementSystemPDMS ;
hito.ttl:2020:                 :applicationSystemClassified :PictureArchivingAndCommunicationSystemPACS ,
hito.ttl:2021:                                              :RadiologyInformationSystem ;
hito.ttl:2450:                               :applicationSystemClassified :MedicalDocumentationSystem ;
hito.ttl:2507:                           :applicationSystemClassified :DecisionSupportSystem ;
hito.ttl:2531:                                                                                          :applicationSystemClassified :DecisionSupportSystem ,
hito.ttl:2532:                                                                                                                       :ProviderOrPhysicianOrderEntrySystemPOE ;
hito.ttl:2540:                                 :applicationSystemClassified :ProviderOrPhysicianOrderEntrySystemPOE ;
hito.ttl:2547:                                          :applicationSystemClassified :ProviderOrPhysicianOrderEntrySystemPOE ;
hito.ttl:2740:                                  :applicationSystemClassified :MedicalDocumentationSystem ;
hito.ttl:2778:                               :applicationSystemClassified :ProviderOrPhysicianOrderEntrySystemPOE ;
hito.ttl:2809:                                              :applicationSystemClassified :EnterpriseResourcePlanningSystem ;
hito.ttl:3304:                               :applicationSystemClassified :LaboratoryInformationSystem ;
hito.ttl:3443:                              :applicationSystemClassified :NursingManagementAndDocumentationSystem ;
hito.ttl:3458:                            :applicationSystemClassified :NursingManagementAndDocumentationSystem ;
hito.ttl:3513:                             :applicationSystemClassified :OperationManagementSystem ;
hito.ttl:3564:                                   :applicationSystemClassified :PatientAdministrationSystem ;
hito.ttl:3579:                                     :applicationSystemClassified :PatientDataManagementSystemPDMS ;
hito.ttl:3647:                                           :applicationSystemClassified :PictureArchivingAndCommunicationSystemPACS ;
hito.ttl:4188:                         :applicationSystemClassified :TeleradiologySystem ;
```

**Comment by KonradHoeffner** [comment]
Remove definitions from hito.ttl and change references to refer to the entries of bb.ttl

- [x] http://hitontology.eu/ontology/ElectronicPatientRecordSystem
- [x] http://hitontology.eu/ontology/PatientDataManagementSystemPDMS
- [x] http://hitontology.eu/ontology/PictureArchivingAndCommunicationSystemPACS
- [x] http://hitontology.eu/ontology/ProviderOrPhysicianOrderEntrySystemPOE
- [x] http://hitontology.eu/ontology/DecisionSupportSystem
- [x] http://hitontology.eu/ontology/EnterpriseResourcePlanningSystem
- [x] http://hitontology.eu/ontology/LaboratoryInformationSystem
- [x] http://hitontology.eu/ontology/MedicalDocumentationSystem
- [x] http://hitontology.eu/ontology/NursingManagementAndDocumentationSystem
- [x] http://hitontology.eu/ontology/OperationManagementSystem
- [x] http://hitontology.eu/ontology/OutpatientManagementSystem
- [x] http://hitontology.eu/ontology/PatientAdministrationSystem
- [x] http://hitontology.eu/ontology/RadiologyInformationSystem
- [x] http://hitontology.eu/ontology/TeleradiologySystem
