### ISSUE TITLE
follow URI naming conventions

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#31]
Only found in hito.ttl yet, but search in the other sources as well. Change the URIs so they follow the naming conventions.

**Examples**
- http://hitontology.eu/ontology/Accident_and_Emergency_department_environment
- https://hitontology.eu/ontology/women_of_reproductive_age

**Comment by KonradHoeffner** [comment]
Fixed for the SNOMED CT entries.

**Comment by VerenaDornauer** [comment]
This might be a free term (citation of an article) and not a SNOMED CT term. I can't find this term in SNOMED CT.

**Comment by KonradHoeffner** [comment]
The standards in standard.ttl have upper case with underscore URIs but that's a special case because those are all abbreviations and in the same way in the database and many of them have that URI in DBpedia as well so I would keep them that way for now.
