### ISSUE TITLE
HL 7 Functional Model

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#33]
ICS > 35 > 35.240 > 35.240.80
ISO/HL7 10781:2015
Health Informatics — HL7 Electronic Health Records-System Functional Model, Release 2 (EHR FM)

We have permission to use it but we need to convert it from the PDF first.
Do not use the hundreds of numbered features because they are intended to specify requirements for software (shall, should, may,...) and are not that well suited to describe existing software products.

- [ ] ask HL7 contacts whether they can provide us with a structured format, even Word would be better than PDF
- [ ] decide whether the x.y entries are features or functions

**Comment by VerenaDornauer** [comment]
Provided in Excel format some times ago. For other if useable please discuss with Franzi

**Comment by KonradHoeffner** [comment]
Das ist doch das gleiche wie der HL7 EHR S-FM den wir schon haben, oder? Da hattest du ja auch eine Tabelle geschickt und wir haben daraus den Katalog https://hitontology.eu/ontology/EhrSfmFeatureCatalogue gebaut. Sehe ich das richtig, dass sich diese Issue hier dann erledigt hat und das nur ein Duplikat ist? Oder ist das doch was ganz anderes?

Hier ist die andere Issue: https://github.com/hitontology/ontology/issues/23
