### ISSUE TITLE
Check connection between features and functions in BB catalogue

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#35]
Erstellt in Tabelle https://docs.google.com/spreadsheets/d/1o8WiAWB3AKDr9BHjF1W07JRbzDtQ-fmPT4IfCToL3RE
In der Ontologie:
- https://hitontology.eu/ontology/BbFeatureCatalogue
- https://hitontology.eu/ontology/BbFunctionCatalogue

**Comment by FranziskaJahn** [comment]
Scheint erledigt zu sein. Habe es stichprobenartig überprüft.
