### ISSUE TITLE
http://hitontology.eu/ontology/GnuHealth

### ISSUE THREAD

**Issue by FranziskaJahn** [hitontology/ontology#37]
http://hitontology.eu/ontology/GnuHealth

Remarks from the developer Luis Falcon:

* Web site : https://www.gnuhealth.org
* License: GPL v3+ (They are missing v3+ in
 https://www.ebi.ac.uk/ols/ontologies/swo/terms?iri=http://www.ebi.ac.uk/swo/license/SWO_1000004).

* Interoperability : ICD10, ICD9, ICD10PCS, WHO ICF, UniprotKB, ICPM,
 Orthanc

* Software Components : GNU Health HMIS, Occhiolino LIMS,
 Emergency Management Systm - EMS, MyGNUHealth PHR, Thalamus,
 Federation Portal, Health Information System

* Features (in addition of what you have documented): Social Medicine,
 Demographics, Domestic violence, Epidemiology, contact tracing,
 infectious diseases, Genetics, bioinformatics

* Operating Systems : GNU/Linux (most distributions), FreeBSD, KDE Neon
 (for PinePhone mobile devices)

* Databases : PostgresSQL for HMIS and HIS // TinyDB (for the
 MyGNUHealth Personal Health Record)

* Languages: English, German, French, Spanish, Chinese, Greek,
 Portuguese, Italian.

**Comment by KonradHoeffner** [comment]
Vielleicht ist das auch schon eingebaut bzw. geändert.

**Comment by MichelleBindel** [comment]
Habe das nachgetragen was möglich war. Es fehlen noch die folgenden Eintragungen die in unserer DB nicht auftauchen:

Interoperability : ICD10PCS, WHO ICF, UniprotKB, Orthanc
Operating Systems : KDE Neon
Databases : TinyDB

**Comment by KonradHoeffner** [comment]
Orthanc ist doch ein anderes Softwareprodukt und kein Interoperabilitätsstandard, deswegen würde ich den auch nicht als Standard hinzufügen. Was sagen die Domänenexperten dazu?

**Comment by KonradHoeffner** [comment]
TinyDB kann ich hinzufügen.

KDE Neon ist kein eigenes OS, sondern baut nur auf Ubuntu Linux auf, daher kannst du Ubuntu auswählen.

**Comment by KonradHoeffner** [comment]
OK, TinyDB ist jetzt verfügbar.

**Comment by KonradHoeffner** [comment]
Es gibt ICD10, kannst du das für ICD10PCS nehmen oder ist das etwas anderes?

**Comment by KonradHoeffner** [comment]
Hast du genauere Informationen zu den fehlenden Interoperabilitätsstandards? Also unabgekürzter Name, Quelle und so weiter. Dann könnte ich die hinzufügen.

**Comment by MichelleBindel** [comment]
@KonradHoeffner Was genau für Infos bräuchtest du denn? Ich hab mal ein wenig recherchiert:

- ICD10PCS (ICD-10 Procedure Coding System): scheint eine Modifikation des ICD10 speziell für Procedure Codes zu sein https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/ICD10PCS/index.html

- WHO ICF (International Classification of Functioning, Disability and Health): classification of health and health-related domains 
https://www.who.int/standards/classifications/international-classification-of-functioning-disability-and-health

- UniprotKB (UniProt Knowledgebase): central hub for the collection of functional information on proteins, with accurate, consistent and rich annotation
https://www.uniprot.org/help/uniprotkb

**Comment by KonradHoeffner** [comment]
Ich habe mir ein paar Instanzen von https://hitontology.eu/ontology/Interoperability angeguckt und es waren eigentlich nur englisches label (gekürzter Name), comment (ungekürzter Name) und Quelle der Informationen. Am besten ein Wikipedia-Artikel, weil es dazu DBpedia-Entsprechungen gibt.

## Beispiel

URI https://hitontology.eu/ontology/ARFF
rdfs:comment Aircraft rescue and firefighting @en
rdfs:label ARFF  @en
dcterms:source dbpedia:Aircraft_rescue_and_firefighting

Dabei fiel mir allerdings auf, dass bei einigen Standards Informationen fehlen, z.B. https://hitontology.eu/ontology/CCAM, dort haben wir nur das Label. Das wäre dann aber eine separate Issue.

In diesem Fall sind die Informationen, die du zu den drei Standards herausgefunden hast alle die ich brauche, danke! Also genauso für die anderen bitte.

**Comment by KonradHoeffner** [comment]
Standard ausgelagert in https://github.com/hitontology/ontology/issues/49.

**Comment by MichelleBindel** [comment]
Informationen zu fehlenden Standards hinzugefügt unter:
https://docs.google.com/spreadsheets/d/170b3u_5k3ilvuVnyVFSRY-oN_tD-sY10qzkIRLVBjKU/edit#gid=0
