### ISSUE TITLE
http://hitontology.eu/ontology/Orthanc

### ISSUE THREAD

**Issue by FranziskaJahn** [hitontology/ontology#38]
http://hitontology.eu/ontology/Orthanc

Feedback vom Entwickler:
•	Besides PostgreSQL, Orthanc also supports MySQL and SQLite.
•	The terminology "mini-PACS" is from my pedagogical vocabulary, but is not widely recognized. I would suggest using "VNA" (Vendor Neutral Archive) instead: https://en.wikipedia.org/wiki/Vendor_Neutral_Archive
•	In the application systems, "RIS-PACS System" could be added (even though Orthanc does not include a RIS, it can be interfaced with through plugins).
•	In the programming languages, JavaScript, Python and HTML could be added.
•	In the organizational units, "Hospital Environment" and "Health Centers" should be added (many private centers use Orthanc, such as radiology, teleradiology, obstetrics, dentists...). It might also be interesting to add an entry about "Software/hardware integrators in the medical field".
•	In the operating systems, "Cross-platform" should be added (Orthanc should work on any UNIX-like system).
•	In the user groups, it might be interesting to add "Physicist", "Network engineer" and "System engineer", all of which apply to Orthanc.
•	It might be interesting to add a new entry "WebAssembly" in the operating systems, and Orthanc could be linked to this entry: https://en.wikipedia.org/wiki/WebAssembly
•	I am unsure where to place this, but Orthanc should be linked with an entry "Viewer" (or maybe more specific terms "Viewer of medical images" or "Web viewer").

Zusätzliche Kommentare FJ:

- check if “WebAssembly” fits better in our “operating system” class or the “interoperability” class

- new application system citations "Vendor Neutral Archive" and “"Web Viewer”. Links to catalogues possible? Direct link of "Vendor Neutral Archive" with Wikipedia?

**Comment by MichelleBindel** [comment]
Eintragungen ergänzt, nicht hinzugefügt werden konnte:
Database: SQLite
Programming languages: HTML 
Interoperability Standards: WebAssembly

@FranziskaJahn "Direct link of "Vendor Neutral Archive" with Wikipedia?" --> Wie würde so ein direct link funktionieren?

**Comment by KonradHoeffner** [comment]
HTML and WebAssembly are not included on purpose.

SQLite is available now.
