### ISSUE TITLE
Database error while entering citation for Application system of SoftwareProduct iPath

### ISSUE THREAD

**Issue by VerenaDornauer** [hitontology/ontology#41]
After entering the citation of the SoftwareProduct ipath (iPath telemedicine network) and attempt to classify it with Telemedicine from the WHOdhi system catalogue, following error warning appeared. The entry was not accepted.

![image](https://user-images.githubusercontent.com/58341156/100901446-1b3aba00-34c4-11eb-8512-78ad4c603e0d.png)

**Comment by KonradHoeffner** [comment]
This is not an ontology error but a database/database-frontend problem. Moved into https://github.com/hitontology/database-frontend/issues/14.
