### ISSUE TITLE
Do all software products have application system types assigned?

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#48]
If no, try to find out and add.

Application system will be renamed to application system type so right now it still has the former label.

**Comment by MichelleBindel** [comment]
Bei den meisten Softwaresystemen habe ich Application System EInträge ergänzt, aber bei vieren konnte ich alleine durch den Namen und Google leider nicht herausfinden welche Software gemeint ist:

- Medicator: die einzige Seite die ich finde ist komplett auf portugiesisch
- Theriak: hier finde ich bloß eine Mineralogie Software, ich gehe mal davon aus die ist nicht gemeint
- Tele DICOM: der Name allein ist zu allgemein und ich finde viel Software die das potentiell sein könnte
- GE Patchspecd PACS: dazu finde ich gar nichts, als PACS von GE habe ich nur Centricity* PACS gefunden

Hat jemand eine genaue Idee welche Software genau gemeint ist?

**Comment by VerenaDornauer** [comment]
Bei Medicator, Theriak, Tele DICOM, GE Patchspecd PACS handelt es sich um evaluierte Anwendungssysteme aus dem Use Case 1 aus Evaluationsstudien. In der Ontologie müsste verzeichnet sein aus welcher Studie die Namen, somit Anwendungssysteme kommen. Es sind teilweise In-house Lösungen, die dann evaluiert wurden:

Medicator und Theriak: jeweils CPOE inkl. CDSS
Tele DICOM: Teleconsultation system
GE Patchspecd PACS: PACS

Eigentlich müsste bei Transfer der Protégé Einträge das application system bereits aufscheinen in der Ontologie, da sie so in Protégé (also im .ttl File) erwähnt wurden. Sonst bitte mit @KonradHoeffner kurzschließen.

Bei Bedarf kann ich per Email meine Dokumentation mit den namentlichen Citations teilen. Bitte in diesem Fall eine kurze Email an mich.

**Comment by MichelleBindel** [comment]
Letzte Einträge sind hinzugefügt. Danke Verena!
