### ISSUE TITLE
Unvollständige Standards

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#49]
Einige Instanzen von https://hitontology.eu/ontology/Interoperability haben zuwenig Informationen, z.B. https://hitontology.eu/ontology/CCAM hat nur das Label. Es sollte immer sowohl der abgekürzte als auch der unabgekürzte Name vorhanden sein und eine Informationsquelle.

@KonradHoeffner: Herausfinden, woher die Standards kommen. Gibt es in dem Quelldokument noch Informationen?
@MichelleBindel: Kannst du versuchen, einige der fehlenden Informationen zu finden? Z.B. was CCAM bedeutet und wo das definiert wird.

**Comment by MichelleBindel** [comment]
```
PREFIX dct: <http://purl.org/dc/terms/>
select ?x (STR(?l) as ?l) ?source (str(?comment) as ?comment) {
?x a hito:Interoperability;
 rdfs:label ?l.
 OPTIONAL {?x dct:source ?source.}
 OPTIONAL {?x rdfs:comment ?comment.}
}
```

**Comment by MichelleBindel** [comment]
x | l | source | comment
-- | -- | -- | --
http://hitontology.eu/ontology/HL7 | HL7 | http://www.hl7.org/ | Health Level 7
http://hitontology.eu/ontology/HL7 | HL7 | http://dbpedia.org/resource/Health_Level_7 | Health Level 7
http://hitontology.eu/ontology/ICD10 | ICD10 | http://dbpedia.org/resource/ICD-10 | International Statistical Classification of Diseases and Related Health Problems
http://hitontology.eu/ontology/ICD10 | ICD10 | https://www.who.int/classifications/icd/icdonlineversions/en/ | International Statistical Classification of Diseases and Related Health Problems
http://hitontology.eu/ontology/DICOM | DICOM | https://www.dicomstandard.org/ | Digital Imaging and Communications in Medicine
http://hitontology.eu/ontology/DICOM | DICOM | http://dbpedia.org/resource/DICOM | Digital Imaging and Communications in Medicine
http://hitontology.eu/ontology/ARFF | ARFF | http://dbpedia.org/resource/Aircraft_rescue_and_firefighting | Aircraft rescue and firefighting
http://hitontology.eu/ontology/CCD | CCD | https://en.wikipedia.org/wiki/Continuity_of_Care_Document | Continuity of Care Document
http://hitontology.eu/ontology/CCR | CCR | https://en.wikipedia.org/wiki/Continuity_of_Care_Record | Continuity of Care Record
http://hitontology.eu/ontology/CDA | CDA | http://www.hl7.org/implement/standards/product_matrix.cfm?Family=CDA | Clinical Document Architecture
http://hitontology.eu/ontology/CDA | CDA | https://en.wikipedia.org/wiki/Clinical_Document_Architecture | Clinical Document Architecture
http://hitontology.eu/ontology/CDISC | CDISC | https://en.wikipedia.org/wiki/Clinical_Data_Interchange_Standards_Consortium | Clinical Data Interchange Standards Consortium
http://hitontology.eu/ontology/CGNS | CGNS | https://en.wikipedia.org/wiki/CGNS | CGNS stands for CFD General Notation System
http://hitontology.eu/ontology/CTS2 | CTS2 | https://wiki.hl7.org/CTS2 | Common Terminology Services 2
http://hitontology.eu/ontology/CTS2 | CTS2 | https://www.omg.org/spec/CTS2/About-CTS2/ | Common Terminology Services 2
http://hitontology.eu/ontology/EDI | EDI | https://docs.oracle.com/cd/E51433_01/fscm92pbr2/eng/fscm/sedi/task_EDIStandards-9f1203.html | Electronic data interchange
http://hitontology.eu/ontology/EDI | EDI | https://en.wikipedia.org/wiki/Electronic_data_interchange | Electronic data interchange
http://hitontology.eu/ontology/EDI | EDI | http://dbpedia.org/resource/Electronic_data_interchange | Electronic data interchange
http://hitontology.eu/ontology/FHIR | FHIR | https://www.hl7.org/fhir/overview.html | Fast Healthcare Interoperability Resources Specification
http://hitontology.eu/ontology/FHIR | FHIR | https://www.hl7.org/implement/standards/product_brief.cfm?product_id=343 | Fast Healthcare Interoperability Resources Specification
http://hitontology.eu/ontology/FHIR | FHIR | http://dbpedia.org/resource/Fast_Healthcare_Interoperability_Resources | Fast Healthcare Interoperability Resources Specification
http://hitontology.eu/ontology/FTP | FTP | https://en.wikipedia.org/wiki/File_Transfer_Protocol | File Transfer Protocol (FTP)
http://hitontology.eu/ontology/FTP | FTP | http://dbpedia.org/resource/File_Transfer_Protocol | File Transfer Protocol (FTP)
http://hitontology.eu/ontology/GDF | GDF | https://en.wikipedia.org/wiki/Geographic_Data_Files | Geographic Data Files (GDF)
http://hitontology.eu/ontology/GDF | GDF | http://dbpedia.org/resource/Geographic_Data_Files | Geographic Data Files (GDF)
http://hitontology.eu/ontology/GDT | GDT | https://en.wikipedia.org/wiki/Geometric_dimensioning_and_tolerancing | Geometric dimensioning and tolerancing
http://hitontology.eu/ontology/GDT | GDT | http://dbpedia.org/resource/Geometric_dimensioning_and_tolerancing | Geometric dimensioning and tolerancing
http://hitontology.eu/ontology/GSM | GSM | https://en.wikipedia.org/wiki/GSM | Global System for Mobile Communications
http://hitontology.eu/ontology/GSM | GSM | http://dbpedia.org/resource/GSM | Global System for Mobile Communications
http://hitontology.eu/ontology/HIPAA | HIPAA | https://www.hhs.gov/hipaa/for-professionals/privacy/index.html | Health Insurance Portability and Accountability Act
http://hitontology.eu/ontology/HIPAA | HIPAA | https://www.hhs.gov/hipaa/index.html | Health Insurance Portability and Accountability Act
http://hitontology.eu/ontology/HIPAA | HIPAA | http://dbpedia.org/resource/Health_Insurance_Portability_and_Accountability_Act | Health Insurance Portability and Accountability Act
http://hitontology.eu/ontology/HPRIM | HPRIM | http://www.interopsante.org/ | Harmoniser et PRomouvoir l'Informatique Médicale
http://hitontology.eu/ontology/HXP | HXP | http://hxp.sourceforge.net/ | Healthcare Xchange Protocol
http://hitontology.eu/ontology/ICD9 | ICD9 | https://www.cdc.gov/nchs/icd/icd9cm.htm | International Classification of Diseases,Ninth Revision, Clinical Modification
http://hitontology.eu/ontology/ICD9 | ICD9 | https://en.wikipedia.org/wiki/List_of_ICD-9_codes | International Classification of Diseases,Ninth Revision, Clinical Modification
http://hitontology.eu/ontology/ICD9 | ICD9 | http://dbpedia.org/resource/ICD-9 | International Classification of Diseases,Ninth Revision, Clinical Modification
http://hitontology.eu/ontology/ICPC2 | ICPC-2 | http://dbpedia.org/resource/ICPC-2 | International Classification of Primary Care, Second edition
http://hitontology.eu/ontology/ICPC2 | ICPC-2 | https://www.who.int/classifications/icd/adaptations/icpc2/en/ | International Classification of Primary Care, Second edition
http://hitontology.eu/ontology/IEPD | IEPD | https://it.ojp.gov/NISS/ | Information Exchange Package Documentation (IEPD) and Justice Standards Clearinghouse
http://hitontology.eu/ontology/IHE | IHE | https://www.ihe.net/ | Integrating the Healthcare Enterprise
http://hitontology.eu/ontology/IHE | IHE | http://dbpedia.org/resource/IHE | Integrating the Healthcare Enterprise
http://hitontology.eu/ontology/IHE_ATNA | IHE-ATNA | https://wiki.ihe.net/index.php/Audit_Trail_and_Node_Authentication | Audit Trail and Node Authentication (ATNA)
http://hitontology.eu/ontology/IHE_BPPC | IHE-BPPC | https://wiki.ihe.net/index.php/Basic_Patient_Privacy_Consents | Basic Patient Privacy Consents (BPPC)
http://hitontology.eu/ontology/IHE_CT | IHE-CT | https://wiki.ihe.net/index.php/Consistent_Time | Consistent Time Integration Profile
http://hitontology.eu/ontology/IHE_EDR | IHE-EDR | https://wiki.ihe.net/index.php/PCC_TF-1/EDR | Emergency Department Referral (EDR) Integration Profile
http://hitontology.eu/ontology/IHE_MHD | IHE-MHD | https://wiki.ihe.net/index.php/Mobile_access_to_Health_Documents_(MHD) | Mobile access to Health Documents (MHD)
http://hitontology.eu/ontology/IHE_MPQ | IHE-MPQ | https://wiki.ihe.net/index.php/Multi-Patient_Queries | Multi-Patient Queries
http://hitontology.eu/ontology/IHE_PAM | IHE-PAM | https://wiki.ihe.net/index.php/Patient_Administration_Management | Patient Administration Management
http://hitontology.eu/ontology/IHE_PCD | IHE-PCD | https://www.ihe.net/ihe_domains/patient_care_devices/ | Patient Care Device
http://hitontology.eu/ontology/IHE_PDQ | IHE-PDQ | https://wiki.ihe.net/index.php/Patient_Demographics_Query | Patient Demographics Query
http://hitontology.eu/ontology/IHE_PDQm | IHE-PDQm | https://wiki.ihe.net/index.php/Patient_Demographics_Query_for_Mobile_(PDQm) | Patient Demographics Query for Mobile (PDQm)
http://hitontology.eu/ontology/IHE_PDQv3 | IHE-PDQv3 | https://wiki.ihe.net/index.php/Patient_Demographics_Query_HL7_v3 | Patient Demographics Query HL7 v3
http://hitontology.eu/ontology/IHE_PIX | IHE-PIX | https://wiki.ihe.net/index.php/Patient_Identifier_Cross-Referencing | Patient Identifier Cross-Referencing
http://hitontology.eu/ontology/IHE_PIXm | IHE-PIXm | https://wiki.ihe.net/index.php/Patient_Identifier_Cross-Reference_for_Mobile_(PIXm) | Patient Identifier Cross-Reference for Mobile (PIXm)
http://hitontology.eu/ontology/IHE_PIXv3 | IHE-PIXv3 | https://wiki.ihe.net/index.php/Patient_Identifier_Cross-Reference_HL7_v3 | Patient Identifier Cross-Reference HL7 v3
http://hitontology.eu/ontology/IHE_QED | IHE-QED | https://wiki.ihe.net/index.php/PCC_TF-1/QED | Query for Existing Data Integration Profile (QED)
http://hitontology.eu/ontology/IHE_RO | IHE-RO | https://wiki.ihe.net/index.php/Radiation_Oncology | Radiation Oncology
http://hitontology.eu/ontology/IHE_SVS | IHE-SVS | https://wiki.ihe.net/index.php/Sharing_Value_Sets | Sharing Value Sets
http://hitontology.eu/ontology/IHE_XCA | IHE-XCA | https://wiki.ihe.net/index.php/Cross-Community_Access | Cross-Community Access
http://hitontology.eu/ontology/IHE_XCF | IHE-XCF | https://wiki.ihe.net/index.php/Cross_Community_Fetch | Cross Community Fetch
http://hitontology.eu/ontology/IHE_XCPD | IHE-XCPD | https://wiki.ihe.net/index.php/Cross-Community_Patient_Discovery | Cross-Community Patient Discovery
http://hitontology.eu/ontology/IHE_XDR | IHE-XDR | https://wiki.ihe.net/index.php/Cross-enterprise_Document_Reliable_Interchange | Cross-enterprise Document Reliable Interchange
http://hitontology.eu/ontology/IHE_XDS | IHE-XDS | https://wiki.ihe.net/index.php/Cross-Enterprise_Document_Sharing | Cross-Enterprise Document Sharing
http://hitontology.eu/ontology/IHE_XDS_MS | IHE-XDS-MS | https://wiki.ihe.net/index.php/PCC_TF-1/XDS-MS | Cross-Enterprise Sharing of Medical Summaries (XDS-MS) Integration Profile
http://hitontology.eu/ontology/IHE_XDS_SD | IHE-XDS-SD | https://wiki.ihe.net/index.php/XDS-SD_Harmonization | XDS-SD Harmonization
http://hitontology.eu/ontology/IHE_XPID | IHE-XPID | https://wiki.ihe.net/index.php/XAD-PID_Change_Management | XAD-PID Change Management
http://hitontology.eu/ontology/IHE_XUA | IHE-XUA | https://wiki.ihe.net/index.php/Cross-Enterprise_User_Assertion_(XUA) | Cross-Enterprise User Assertion (XUA)
http://hitontology.eu/ontology/ISO13606 | ISO 13606 | https://www.iso.org/standard/67868.html | Health informatics — Electronic health record communication — Part 1: Reference model
http://hitontology.eu/ontology/ISO13606 | ISO 13606 | http://dbpedia.org/resource/EN_13606 | Health informatics — Electronic health record communication — Part 1: Reference model
http://hitontology.eu/ontology/ISOIEC11756_1999 | ISO/IEC 11756:1999 | https://www.iso.org/standard/29268.html | Information technology — Programming languages
http://hitontology.eu/ontology/LOINC | LOINC | https://loinc.org/ | Logical Observation Identifiers Names and Codes (LOINC)
http://hitontology.eu/ontology/LOINC | LOINC | https://en.wikipedia.org/wiki/LOINC | Logical Observation Identifiers Names and Codes (LOINC)
http://hitontology.eu/ontology/LOINC | LOINC | http://dbpedia.org/resource/LOINC | Logical Observation Identifiers Names and Codes (LOINC)
http://hitontology.eu/ontology/MPPS | MPPS | https://www.medicalconnections.co.uk/tags/MPPS | Modality Performed Procedure Step Service
http://hitontology.eu/ontology/MedDRA | MedDRA | https://en.wikipedia.org/wiki/MedDRA | Medical Dictionary for Regulatory Activities
http://hitontology.eu/ontology/MedDRA | MedDRA | http://dbpedia.org/resource/MedDRA | Medical Dictionary for Regulatory Activities
http://hitontology.eu/ontology/NCPDP | NCPDP | https://ncpdp.org/Standards-Development/Standards-Information | national council for prescription drug programs
http://hitontology.eu/ontology/NCPDP | NCPDP | http://dbpedia.org/resource/National_Council_for_Prescription_Drug_Programs | national council for prescription drug programs
http://hitontology.eu/ontology/NHS | NHS | http://dbpedia.org/resource/National_Health_Service | national health service
http://hitontology.eu/ontology/NIEM | NIEM | https://www.niem.gov/ | National Information Exchange Model
http://hitontology.eu/ontology/NIEM | NIEM | http://dbpedia.org/resource/National_Information_Exchange_Model | National Information Exchange Model
http://hitontology.eu/ontology/NIfTI | NIfTI | https://nifti.nimh.nih.gov/ | Neuroimaging Informatics Technology Initiative
http://hitontology.eu/ontology/OASIS | OASIS | https://www.oasis-open.org/standards | Organization for the Advancement of Structured Information Standards (OASIS)
http://hitontology.eu/ontology/OASIS | OASIS | https://en.wikipedia.org/wiki/OASIS_(organization) | Organization for the Advancement of Structured Information Standards (OASIS)
http://hitontology.eu/ontology/OMOP | OMOP | https://www.ohdsi.org/data-standardization/the-common-data-model/ | OMOP Common Data Model
http://hitontology.eu/ontology/OPS | OPS | https://en.wikipedia.org/wiki/Open_Pluggable_Specification | Open Pluggable Specification
http://hitontology.eu/ontology/SAML | SAML | https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language | Security Assertion Markup Language
http://hitontology.eu/ontology/SAML | SAML | http://dbpedia.org/resource/Security_Assertion_Markup_Language | Security Assertion Markup Language
http://hitontology.eu/ontology/SDMX_HD | SDMX-HD | https://wiki.openmrs.org/display/docs/SDMX-HD | Statistical Data and Metadata Exchange (SDMX) for the Health Domain
http://hitontology.eu/ontology/SMTP | SMTP | https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol | Simple Mail Transfer Protocol
http://hitontology.eu/ontology/SMTP | SMTP | http://dbpedia.org/resource/Simple_Mail_Transfer_Protocol | Simple Mail Transfer Protocol
http://hitontology.eu/ontology/SNOMED_CT | SNOMED CT | http://www.snomed.org/ | systematically organized computer processable collection of medical terms
http://hitontology.eu/ontology/SNOMED_CT | SNOMED CT | https://en.wikipedia.org/wiki/SNOMED_CT | systematically organized computer processable collection of medical terms
http://hitontology.eu/ontology/SNOMED_CT | SNOMED CT | http://dbpedia.org/resource/SNOMED_CT | systematically organized computer processable collection of medical terms
http://hitontology.eu/ontology/SOAP | SOAP | https://en.wikipedia.org/wiki/SOAP | Simple Object Access Protocol
http://hitontology.eu/ontology/SOAP | SOAP | http://dbpedia.org/resource/SOAP | Simple Object Access Protocol
http://hitontology.eu/ontology/STS | STS | http://dbpedia.org/resource/Microsoft_Live_Labs_Security_Token_Service | Security token service? (MS Live)
http://hitontology.eu/ontology/SVG | SVG | https://en.wikipedia.org/wiki/Scalable_Vector_Graphics | Scalable Vector Graphics
http://hitontology.eu/ontology/SVG | SVG | http://dbpedia.org/resource/Scalable_Vector_Graphics | Scalable Vector Graphics
http://hitontology.eu/ontology/TARMED | TARMED | http://www.tarmedsuisse.ch/ | Tarif Médical
http://hitontology.eu/ontology/TARMED | TARMED | http://dbpedia.org/resource/TARMED | Tarif Médical
http://hitontology.eu/ontology/UMLS | UMLS | https://www.nlm.nih.gov/research/umls/index.html | Unified Medical Language System
http://hitontology.eu/ontology/UMLS | UMLS | http://dbpedia.org/resource/Unified_Medical_Language_System | Unified Medical Language System
http://hitontology.eu/ontology/WADO | WADO | https://www.dicomstandard.org/dicomweb/retrieve-wado-rs-and-wado-uri/ | Web Access to DICOM Objects (WADO)
http://hitontology.eu/ontology/WSDL | WSDL | https://www.w3.org/TR/wsdl.html | Web Services Description Language
http://hitontology.eu/ontology/WSDL | WSDL | http://dbpedia.org/resource/Web_Services_Description_Language | Web Services Description Language
http://hitontology.eu/ontology/XACML | XACML | http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html | eXtensible Access Control Markup Language
http://hitontology.eu/ontology/XACML | XACML | http://dbpedia.org/resource/XACML | eXtensible Access Control Markup Language
http://hitontology.eu/ontology/XML | XML | http://dbpedia.org/resource/XML | Extensible Markup Language
http://hitontology.eu/ontology/XML | XML | https://www.w3.org/XML/ | Extensible Markup Language
http://hitontology.eu/ontology/XPath | XPath | http://dbpedia.org/resource/XPath | XML Path Language
http://hitontology.eu/ontology/XPath | XPath | https://www.w3.org/TR/1999/REC-xpath-19991116/ | XML Path Language
http://hitontology.eu/ontology/XSD | XSD | https://www.w3.org/TR/xmlschema11-1/ | W3C XML Schema Definition Language (XSD)
http://hitontology.eu/ontology/XSD | XSD | http://dbpedia.org/resource/XML_Schema_(W3C) | W3C XML Schema Definition Language (XSD)
http://hitontology.eu/ontology/YAML | YAML | https://en.wikipedia.org/wiki/YAML | YAML (a recursive acronym for "YAML Ain't Markup Language") is a human-readable data-serialization language.
http://hitontology.eu/ontology/YAML | YAML | http://dbpedia.org/resource/YAML | YAML (a recursive acronym for "YAML Ain't Markup Language") is a human-readable data-serialization language.
http://hitontology.eu/ontology/NDR | NDR |   | was soll das sein?
http://hitontology.eu/ontology/OPCS44 | OPCS44 |   | National Clinical Coding Standards OPCS-4
http://hitontology.eu/ontology/Arden | Arden | http://dbpedia.org/resource/Arden_syntax |  
http://hitontology.eu/ontology/CCA | CCA | http://www.cpaa.org.uk/care-standards-handbook.html |  
http://hitontology.eu/ontology/CMS3_0 | CMS 3.0 | https://www.cms.gov/Regulations-and-Guidance/Guidance/CMSRecordsSchedule/index |  
http://hitontology.eu/ontology/CMS3_0 | CMS 3.0 | https://www.cms.gov/Regulations-and-Guidance/Regulations-and-Guidance |  
http://hitontology.eu/ontology/CORBA | CORBA | http://dbpedia.org/resource/Common_Object_Request_Broker_Architecture |  
http://hitontology.eu/ontology/CertifiedHITProduct | Certified HIT Product | https://chpl.healthit.gov/#/search |  
http://hitontology.eu/ontology/Continua | Continua | https://www.pchalliance.org/continua-design-guidelines |  
http://hitontology.eu/ontology/HSCIC_ITK | HSCIC-ITK | http://dbpedia.org/resource/HSCIC |  
http://hitontology.eu/ontology/ICPM | ICPM | http://dbpedia.org/resource/ICPM |  
http://hitontology.eu/ontology/IHE_XDS_I | IHE-XDS-I | http://hitontology.eu/ontology/he |  
http://hitontology.eu/ontology/KML | KML | http://dbpedia.org/resource/Keyhole_Markup_Language |  
http://hitontology.eu/ontology/OpenEHR | Open EHR | https://en.wikipedia.org/wiki/OpenEHR |  
http://hitontology.eu/ontology/OpenEHR | Open EHR | http://dbpedia.org/resource/OpenEHR |  
http://hitontology.eu/ontology/REST | REST | http://dbpedia.org/resource/Representational_state_transfer |  
http://hitontology.eu/ontology/SCP_ECG | SCP-ECG | http://dbpedia.org/resource/SCP-ECG |  
http://hitontology.eu/ontology/SMART | SMART | https://en.wikipedia.org/wiki/SMART_criteria |  
http://hitontology.eu/ontology/SMART | SMART | http://dbpedia.org/resource/SMART_criteria |  
http://hitontology.eu/ontology/X12 | X12 | http://dbpedia.org/resource/X12 |  
http://hitontology.eu/ontology/ATC | ATC |   |  
http://hitontology.eu/ontology/CAM | CAM |   |  
http://hitontology.eu/ontology/CCAM | CCAM |   |  
http://hitontology.eu/ontology/CDISG | CDISG |   |  
http://hitontology.eu/ontology/HL7_FHIR | HL7 FHIR |   |  
http://hitontology.eu/ontology/HPRIM-XML | HPRIM-XML |   |  
http://hitontology.eu/ontology/HPRIM2_1 | HPRIM-2.1 |   |  
http://hitontology.eu/ontology/IHE_XCA_I | IHE-XCA-I |   |  
http://hitontology.eu/ontology/IHE_XDSa | IHE-XDS.a |   |  
http://hitontology.eu/ontology/IHE_XDSb | IHE-XDS.b |   |  
http://hitontology.eu/ontology/NGAP | NGAP |   |  
http://hitontology.eu/ontology/PN13 | PN13 |

**Comment by MichelleBindel** [comment]
Fast vollständige Liste unter:
https://docs.google.com/spreadsheets/d/170b3u_5k3ilvuVnyVFSRY-oN_tD-sY10qzkIRLVBjKU/edit#gid=0

Mail wegen der noch fehlenden Infos an Maryam gesendet.

**Comment by KonradHoeffner** [comment]
Können wir kurz am Montag 9:15 bei der Telco vorstellen. Ich warte noch mit dem Konvertieren, falls Maryam noch Tipps hat.
Hast du auf Medfloss.org noch was gefunden? <https://www.medfloss.org/project-wizard?f[0]=taxonomy_vocabulary_6%3A162> und dann "Filter by Standard" -> "More".

**Comment by MichelleBindel** [comment]
Maryam hat nochmal bestätigt, dass die Standards von Medfloss.org stammen, darüber habe ich  jetzt auch die restlichen Infos gefunden.
@KonradHoeffner du könntest jetzt loslegen mit dem konvertieren 👍

**Comment by KonradHoeffner** [comment]
@FranziskaJahn überprüft es nochmal und sagt dann Bescheid und dann konvertiere ich es.

- CDA ist doppelt drin, einmal mit HL7 und einmal ohne.
- bei HL7 Standards sollte HL7 mit da stehen.

**Comment by FranziskaJahn** [comment]
Ich bin die Liste durchgegangen und habe ein paar Zeilen eingefärbt und jeweils in die Spalte "COMMENT" etwas reingeschrieben.
@MichelleBindel Gehe bitte noch mal die Kommentare durch. Wenn du damit fertig bist, kann @KonradHoeffner dann konvertieren.

**Comment by KonradHoeffner** [comment]
@MichelleBindel: Wie ist der Status, kann ich es konvertieren?

**Comment by MichelleBindel** [comment]
@KonradHoeffner Ist alles fertig! Kannst direkt konvertieren :-)

**Comment by KonradHoeffner** [comment]
Seid ihr sicher, dass mit ARFF wirklich "Aircraft rescue and firefighting" gemeint ist? Was soll denn das für ein Dateninteroperabilitätsstandard im Krankenhaus sein?

**Comment by KonradHoeffner** [comment]
Habe die Tabelle nochmal leicht angepasst und STS substandard of Windows_Live entfernt, da wir es nicht als Standard haben.

**Comment by MichelleBindel** [comment]
@KonradHoeffner stimmt, ich habe gerade nochmal gesucht und das einzige Softwareprodukt auf Medfloss was ARFF nutzt ist Weka, und da ist ARFF ein eigens implementiertes File Format:
https://www.cs.waikato.ac.nz/ml/weka/arff.html

**Comment by KonradHoeffner** [comment]
Soll ich es dann ganz rauslöschen oder nur umbenennen? Wenn es nur einmal benutzt wird, ist es ja eher ein Dateiformat als ein Interoperabilitätsformat.

**Comment by KonradHoeffner** [comment]
Ich lösche es erstmal raus. Weka ist soweit ich weiß auch keine Krankenhaussoftware.

**Comment by KonradHoeffner** [comment]
- [x] convert
- [x] integrate in ontology
- [x] upload to SPARQL endpoint
- [ ] check and update database

See https://hitontology.eu/ontology/Interoperability

**Comment by KonradHoeffner** [comment]
When updating the interoperability standards, the software product to standard table may be cleared. Populate again with the saved values below.
- [x] fix the URIs in the database and in the table below by removing spaces

swp_suffix | io_suffix
-- | --
GnuHealth | ICD10
GnuHealth | HL7
GnuHealth | HL7_FHIR
Orthanc | DICOM
Orthanc | REST
iPath | DICOM
BetterMeds | HL7_FHIR
BetterMeds | OpenEHR
BetterMeds | SNOMED_CT
GnuHealth | ICPM
GnuHealth | ICD9
OpenMRS | CDA
OpenMRS | HL7_FHIR
OpenMRS | HL7
OpenEMR | CDA
OpenEMR | DICOM
OpenEMR | REST
OpenEMR | HL7_FHIR
OpenEMR | HL7
OpenEMR | SMART
OpenClinicGA | LOINC
OpenClinicGA | HL7
OpenClinicGA | ICD10
OpenClinicGA | ICPC2
OpenClinicGA | SNOMED_CT
OpenClinicGA | DICOM
OpenClinicGA | HL7_FHIR
PACS1 | DICOM
PACS1 | HL7
PACS1 | IHE
PACS2 | DICOM
Elexis | ICPC2
HospitalRun | HL7_FHIR
Medkey | OpenEHR
Medkey | HL7
OpenMRS | HL7_CCD

- [x] insert new values

**Comment by KonradHoeffner** [comment]
## Tabelle
- [x] Arden Syntax zu HL7 Arden Syntax umbenennen und verbinden mit HL7
- [x] ICD9,10,11 Oberstandard ICD erzeugen und verbinden
- [x] fehlende HL7 Oberstandard-Verknüpfungen hinzufügen

## Rest
- [x] konvertieren
- [x] auf GitHub aktualisieren
- [x] im Endpunkt aktualisieren
- [x] in Datenbank übernehmen: Arden -> HL7_Arden, CTS2 -> HL7_CTS2
