### ISSUE TITLE
WHOdhi - Issue Health System Managers, 3.2 Supply Chain Management

### ISSUE THREAD

**Issue by VerenaDornauer** [hitontology/ontology#51]
Gesamte Sektion (3.2 Supply Chain Management) muss manuell überprüft werden @KonradHoeffner 

Ungereimtheiten bei auswählbaren Features. Auswählbare Einträge in Datenbank stimmten nicht mit der WHOdhi Klassifikation über ein.

**Comment by KonradHoeffner** [comment]
hito:WhoDhiSupplyChainManagement

**Comment by KonradHoeffner** [comment]
- [x] Quelltabelle überprüfen und korrigieren
- [x] konvertieren
- [x] in die Ontologie integrieren
- [x] in der Datenbank umbenennen inklusive Verweisen (Verweise aktualisieren nicht nötig, da nur die Labels umbenannt wurden und die URIs stabil gehalten wurden)
