### ISSUE TITLE
Softwareprodukte ohne Details

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#56]
- [ ] GE Patchspecd PACS
- [ ] e Doc

Es ist keine Quelle angegeben, gibt es dazu irgendetwas, Homepage, Repository oder so? Ich kann nirgendwo Details dazu finden. Bitte ergänzen.

**Comment by MichelleBindel** [comment]
Das GE Patchspecd PACS stammt auf jeden Fall aus dem Use Case 1 mit den Evaluationsstudien, e Doc eventuell auch. Laut @vdornauer sind das teils Inhouse Lösungen die dann nicht unbedingt irgendwo in einem Repository hinterlegt oder auf einer Website beschrieben sind.

**Comment by KonradHoeffner** [comment]
Mehr Details gibt es dazu nicht, da in den Studien nicht mehr stand. Bitte als Kommentar hinzufügen. Es sind 24.

**Comment by VerenaDornauer** [comment]
Softwareprodukte aus Studien, wo Beschreibung auf Studienbeschreibungen basieren:

- [x] e-Chasqui
- [x] Cerner Millenium PowerOrders
- [x] CSC MedChart
- [x] Cerner Soarian CPOE platform
- [x] Medicator
- [x] Theriak
- [x] TeleDICOM
- [x] AGFA PACS IMPAX
- [x] AGFA RIS Elefante
- [x] GE Pathspecd PACS
- [x] SAP R3 Business Process Control System software
- [x] Metavision
- [x] PIK
- [x] HNA Millenium
- [x] Cerner First-net
- [x] eDoc
- [x] Eclipsys Continuum 2000 CDS
- [x] Abbott I-Stat
- [x] Sysmex XS haematology analyser

**Comment by KonradHoeffner** [comment]
Danke Verena!

- [x] @MichelleBindel: Für jedes Softwareprodukt X aus der Liste: Zu X bitte den Kommentar hinzufügen und mir dann Bescheid geben und mich assignen hier.
- [x] @KonradHoeffner: Beim nächsten Datenbank-Ontologie merge mit übernehmen.

**Comment by MichelleBindel** [comment]
@KonradHoeffner Kommentare sind eingetragen und werden beim nächsten Merge übernommen

**Comment by KonradHoeffner** [comment]
- [x] letzter Merge war vor 14 Tagen, daher noch einmal mergen

**Comment by KonradHoeffner** [comment]
Merge fügt keine neuen Tripel hinzu, Kommentare sind schon vorhanden, issue ist damit erledigt. Vielen Dank @VerenaDornauer  und @MichelleBindel!
