### ISSUE TITLE
Fix Labels of WHO DHI catalogue entries

### ISSUE THREAD

**Issue by VerenaDornauer** [hitontology/ontology#59]
WHOdhi - 2. Healthcare Provider

- [x] 2.9.3 Report adverse drug events
- [x] 2.10.1 Transmit diagnostic result to healthcare provider
- [x] 2.10.2 Transmit and track diagnostic orders
- [x] 2.10.3 Capture diagnostic results from digital devices
- [x] 2.10.4 Track biological specimen

can not be selected for classifying features. Maybe they are missing in the **WHOdhi Feature Catalogue** in the Database?

@KonradHoeffner , please investigate, thank you!

**Comment by KonradHoeffner** [comment]
## Fix labels in the spreadsheet
- [x] 1.0 Clients
- [x] 2.0 Healthcare Providers (the only mistakes were the already mentioned)
- [x] 3.0 Health System Managers
- [x] 4.0 Data Services

All the other entries and WHO DHI catalogues were OK.

**Comment by KonradHoeffner** [comment]
I wrote an email to Dr. Garrett Mehl and asked if they maybe already have it available in a structured data format.

**Comment by KonradHoeffner** [comment]
- [x] fix in spreadsheet
- [x] fix in ontology repository
- [x] upload to SPARQL endpoint
- [x] fix in database

**Comment by KonradHoeffner** [comment]
@VerenaDornauer: All entries are fixed in the ontology and the database now. Please check, it should now work in the frontend as well.
If not, please reopen and state what isn't working.
