### ISSUE TITLE
Create blue book feature, function and application system catalogues

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#6]
Page 123 in the written book second edition, table 6.7.

**Comment by KonradHoeffner** [comment]
- [x] fix name of hito:BbReferenceModel to http://hitontology.eu/ontology/BbReferenceModelFunctionCatalogue
- [x] Blue Book Feature Catalogue https://hitontology.eu/ontology/BbFeatureCatalogue
- [x] Blue Book Function Catalogue https://hitontology.eu/ontology/BbFunctionCatalogue
- [x] Blue Book Application System Catalogue https://hitontology.eu/ontology/BbApplicationSystemCatalogue

**Comment by KonradHoeffner** [comment]
One application system catalogue:
Chapters 6.4.1 till 6.4.13: each heading is a classified application system.
6.4.14 table: Each cell in the first column is also a classified application system.

**Comment by KonradHoeffner** [comment]
https://hitontology.eu/ontology/BbOperationManagementSystemFeatureCatalogue is missing entries.
Merge all tables 6.1 to 6.13, which list single features. All into one catalogue.

**Comment by KonradHoeffner** [comment]
@FranziskaJahn: Ich habe mal nachgeforscht, der existierende Function- und Featurekatalog stammt aus dem blue book PDF manuscript von 2010 Seite 142 Tabelle 6-7: "typical supported hospital functions and related features of the operation management system".

**Comment by ThomasPause** [comment]
BB Operation Management System Feature Catalogue's extraction is ready and can be found [here](https://docs.google.com/spreadsheets/d/1o8WiAWB3AKDr9BHjF1W07JRbzDtQ-fmPT4IfCToL3RE/edit#gid=1234838117).

**Comment by KonradHoeffner** [comment]
The results are online at 
- https://hitontology.eu/ontology/BbOperationManagementSystemFeatureCatalogue
- https://hitontology.eu/ontology/BbOperationManagementSystemFunctionCatalogue
- https://hitontology.eu/ontology/BbApplicationComponentApplicationSystemCatalogue

**Comment by KonradHoeffner** [comment]
This was discussed in the SNIK Jour Fixe 2020-04-21.

- [x] The name "Blue Book Operation Management System Function Catalogue" is wrong now because an Operation Management System is an application system for medical operations (surgeries), which only applies to the original table 6.7. Rename the catalogues to "Blue Book Architecture Function/Feature/Application System Catalogue"

Each of those tables represents a different application component:

| Table  | Application System | URI |
| ------------- | ------------- | ------------- |
| 6.1  | Patient Administration System  | https://www.snik.eu/ontology/bb/PatientAdministrationSystem |
| 6.2  |  Medical Documentation System | https://www.snik.eu/ontology/bb/MedicalDocumentationSystem |
| 6.3  | Nursing Management and Documentation System  | https://www.snik.eu/ontology/bb/NursingManagementAndDocumentationSystem |
| 6.4  | Outpatient Management System  | https://www.snik.eu/ontology/bb/OutpatientManagementSystem |
| 6.5  | Physician Order Entry System  | we only have https://www.snik.eu/ontology/bb/ComputerizedPhysicianOrderEntrySystem |
| 6.6  |  Patient Data Management System |  https://www.snik.eu/ontology/bb/PatientDataManagementSystem |
| 6.7  |  Operation Management System | https://www.snik.eu/ontology/bb/OperationManagementSystem |
| 6.8  | Radiology Information System  | https://www.snik.eu/ontology/bb/RadiologyInformationSystem |
| 6.9  | Radiology Information System (hier müsste PACS stehen denke ich)  | https://www.snik.eu/ontology/bb/PictureArchivingAndCommunicationSystem |
| 6.10  | Laboratory Information System  | https://www.snik.eu/ontology/bb/LaboratoryInformationSystem |
| 6.11  | Enterprise Resource Planning System  | https://www.snik.eu/ontology/bb/EnterpriseResourcePlanningSystem |
| 6.12  | Data Warehouse System  | https://www.snik.eu/ontology/bb/DataWarehouseSystem |
| 6.13  | Document Archiving System  | https://www.snik.eu/ontology/bb/DocumentArchivingSystem |

**Comment by KonradHoeffner** [comment]
Continuation of the discussion of the SNIK Jour Fixe 2020-04-21:

- es gibt ein feature sowohl beim RIs als auch beim anderen
- sind features von verschiedenen funktionen identisch?
- in BB catalog change URL to BB
- features als data properties in SNIK existent?
- beim Lesen ist es relativ klar
- wenn tabellen formal representiert werden, muss dokumentiert sein in der ontologie, aus welchen Tabellen aus welcher Seite das herkommt
- Hintergrund muss nachvollziehbar sein
- wenn features da sind, zb open source RIS software, nutzen des Wissens aus dem BB, ist das überhaupt richtig so? Ist eine Hilfestellung.
- Lange Liste von Features, die schonmal mit RIS genannt wurden. 
- meta:Feature aus 
- todo : systematisierung der meta:Feature im bb
- wir haben zwei existierende: über die Functions und über die Anwendungssysteme
- Zuordnung aus den existierenden Katalogtabellen in den SNIK-Datensatz integrieren
- sowohl Bezug zu Application Component als auch zu Functions dort ablegen
- bb: "Execution of radiological examinations" is sub function of "Execution of Diagnostic, Therapeutic and Nursing Procedures"

**Comment by KonradHoeffner** [comment]
- [x] connect HITO to BB

When we connect HITO with BB using the HITO BB catalogue, we now create our own instances of catalogues and classified application systems, features and functions. It would be better to use BB classes directly. However:

- in SNIK they are classes but in HITO instances
- we need the HITO types hito:ClassifiedFeature on so on, and don't want to assign them in SNIK
- we also need to connect XClassified to its catalogue with XClassified as the subject, so we would need to add triples to BB classes from within HITO

Due to those problems, using BB classes directly is not possible. So I will implement the following compromise:

- [x] add a dcterms:source column to the BB spreadsheets and prefill it with the catalogue entry suffix but BB prefix
- [x] create a SPARQL instance existence checker to see which ones this misses, see https://github.com/hitontology/csv2rdf/blob/master/check.py
- [x] try to save the misses using the SNIK Graph search or daring URL guessing, remove what is not salvageable
- [x] add dcterms:source support to the relevant templates in https://github.com/hitontology/csv2rdf
- [x] use dc:source with "Table${x}.${y}" values to note source for the features, some of which may be included in multiple tables
- [x] merge duplicated functions
- [x] merge features (keep lines though, just align the URIs)
- [x] update the result in bb.rdf
- [x] review bb.rdf by Konrad
- [x] split the values of the "super" column in the subfeature template
- [x] upload the new version of HITO to the SPARQL endpoint
- [x] review of the results by Konrad
- [x] test the catalogues in the instance generator

**Comment by KonradHoeffner** [comment]
- [ ] features als data properties in SNIK existent?
- [ ] Hintergrund muss nachvollziehbar sein
- [ ] wenn features da sind, zb open source RIS software, nutzen des Wissens aus dem BB, ist das überhaupt richtig so? Ist eine Hilfestellung.
- [ ] Lange Liste von Features, die schonmal mit RIS genannt wurden. 
- [ ] todo : systematisierung der meta:Feature im bb
- [ ] wir haben zwei existierende: über die Functions und über die Anwendungssysteme
- [ ] Zuordnung aus den existierenden Katalogtabellen in den SNIK-Datensatz integrieren
- [ ] sowohl Bezug zu Application Component als auch zu Functions dort ablegen
- [ ] bb: "Execution of radiological examinations" is sub function of "Execution of Diagnostic, Therapeutic and Nursing Procedures"

**Comment by KonradHoeffner** [comment]
Removed the task to create SKOS links between SNIK and HITO BB catalogue entries because fac7e708 adds links via dcterms:source instead.

**Comment by KonradHoeffner** [comment]
As the catalogues are finished, close this issue. Additions are moved into issue https://github.com/hitontology/ontology/issues/44.
