### ISSUE TITLE
LIS Katalog

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#61]
Von https://www.pathologyinformatics.org/toolkit.php Excel-Tabelle prüfen, ob wir das als LIS-Katalog verwenden können, wenn ja einkürzen, und dann im gleichen Format wie die anderen Kataloge im HITO Google-Drive Ordner ablegen und Konrad Bescheid geben und assignen dieser Issue.

**Comment by MichelleBindel** [comment]
Dokument mit allen Ebenen bzw. gekürzt auf zwei Ebenen:
https://docs.google.com/spreadsheets/d/1aBHyj6binln6tZMGHApF0-1GM15uSChl_P7uYvTbK24/edit?usp=sharing
--> gelb markierte Felder wären nützlich für LIS Classifieds, betreffen Features die noch nicht durch andere Kataloge abgedeckt werden

Die dritte Ebene ist zu detailliert, keine konkrete Bezeichnungen eher Beschreibungen des Features in mehreren Sätzen.
Auf der zweiten Ebene wiederholen sich Begriffe oft. Die Bezeichnungen sind hier nicht ausführlich genug, die einzelnen Wörter sind teilweise nicht konkret genug um sie als Feature zu verstehen.

Urteil: In roher Form leider nicht als Katalog für HITO geeignet. Evtl. könnte man die dritte Ebene für relevante Abschnitte einkürzen und so verwenden. Oder die Begriffe der zweiten Ebene etwas ausführlicher formulieren..

**Comment by KonradHoeffner** [comment]
@FranziskaJahn: Bitte prüfen, ob es sich noch retten lässt, wie von @MichelleBindel vorgeschlagen.

Wenn ja, dann Katalog erstellen.

Wenn nein, dann WHO DHI benutzen.

**Comment by KonradHoeffner** [comment]
Nach @MichelleBindel zu aufwändig. Wenn doch wieder geplant, Issue bitte wieder öffnen.
