### ISSUE TITLE
add enterprise function hierarchy

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#63]
We have subFeatureOf but no subFunction of, do we need that?
@FranziskaJahn states that there should be a function hierarchy in the BB catalogue, which is managed in https://docs.google.com/spreadsheets/d/1o8WiAWB3AKDr9BHjF1W07JRbzDtQ-fmPT4IfCToL3RE/edit#gid=1532284086 but we don't have it there yet.

Investigate.

**Comment by KonradHoeffner** [comment]
Decision 2021-07-05: Yes.

- [x] @KonradHoeffner: Add subFunction property.
- [x] @FranziskaJahn: Add hierarchy to spreadsheet.
- [ ] then @KonradHoeffner: add to the ontology

**Comment by FranziskaJahn** [comment]
Tabelle https://docs.google.com/spreadsheets/d/1o8WiAWB3AKDr9BHjF1W07JRbzDtQ-fmPT4IfCToL3RE/edit#gid=1532284086 hat nun eine neue ausgefüllte Spalte subFunctionOf.

**Comment by KonradHoeffner** [comment]
Danke! Da in der Spalte die Labels stehen, habe ich die Labels über einen VLOOKUP in die URLs umgewandelt und das Umwandlungsskript angepasst.
Dabei fiel auf, dass "scheduling and resource planning with the patient transport service" einem "Patient Management" zugeordnet war, was es nicht gibt. Habe die Superfunction davon zu "Supply management, scheduling and resource allocation" geändert, da es das gibt und das mir am passendsten erscheint.
