### ISSUE TITLE
HITCOMP

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#75]
@vdornauer erforscht HITCOMP, ob es sich für eine neue Instanz eignet. Dabei müsste aber auch eine neue Klasse angelegt werden, da es sich um Kompetenzen handelt.

@KonradHoeffner präferiert einfache Modellierung ohne Katalog, wenn möglich.

**Comment by vdornauer** [comment]
Roles von HITCOMP anstelle der Classe UserGroup von SNOMED-CT verwenden - es gibt 270 Rollen, ein Mapping müsste manuell erfolgen der jetzigen UserGroup Instanzen zu den Instanzen der Roles von HITCOMP

Unter: [http://hitcomp.org/roles/](url) bekommt man schnell einen Überblick. Mit Übernahme in HITO von Filtermethoden als Subclasses für Unterteilung der 270 Rollen

Von HITCOMP können Daten per Excel oder CSV exportiert werden. Wir müssten hier jedoch mit den Erstellern von HITCOMP dies besprechen.

Cave: HITCOMP ist an sich keine Ontologie. Open-Linked Data können leider nicht zu tragen kommen.

**Comment by vdornauer** [comment]
@vdornauer Kontakt aufnehmen mit HITCOMP Erstellern. Mail an info@hitcomp.org

**Comment by vdornauer** [comment]
@FranziskaJahn added, so Franziska can see what is possible

**Comment by KonradHoeffner** [comment]
Wurde jetzt anders gelöst, Issue hat sich erledigt.
