### ISSUE TITLE
Lizenz license für die Ontologie?

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#82]
Haben wir darüber schon mal gesprochen? Bei SNIK haben wir ja die ziemlich restriktive CC-BY-NC-SA 4.0 genommen, weil darin Textbücher vorkommen, aber das haben wir in diesem Fall ja nicht. Ähnlich wie bei Wikipedia schlage ich die Lizenzen [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) und die [GNU Free Documentation License](https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_GNU_Free_Documentation_License) vor. Die Frage ist auch, ob wir zwischen den Daten und der Ontologie unterscheiden müssen.

**Comment by KonradHoeffner** [comment]
In Nürnberg besprechen beim großen Meeting.

**Comment by KonradHoeffner** [comment]
Das haben wir leider nicht geschafft, needs discussion mit @AlfredWinter.

**Comment by KonradHoeffner** [comment]
Möglichst Offene nehmen.
@KonradHoeffner: Ein paar offene Lizenzen vorschlagen, in der Runde entscheiden.
@AlfredWinter: Bitte dann an HL7 schreiben, ob die damit einverstanden sind.
SNOMED an sich benötigt auch eine Lizenz je nach Land.
@vdornauer fragen.

**Comment by KonradHoeffner** [comment]
@FranziskaJahn hat die Lizenzen am 13.1. mit EA besprochen.

Meine Vorschläge, wobei ich die CC BY-SA 4.0 problematisch finde und CC0 oder CC BY 4.0 in dieser Reihenfolge stark bevorzuge:

## CC0 "No rights reserved"

Am offensten und meiner Meinung nach am besten für wissenschaftliche Daten ist CC0.

Siehe https://creativecommons.org/share-your-work/public-domain/cc0/

CC0 enables scientists, educators, artists and other creators and owners of copyright- or database-protected content to waive those interests in their works and thereby place them as completely as possible in the public domain, so that others may freely build upon, enhance and reuse the works for any purposes without restriction under copyright or database law.

Putting a database or dataset in the public domain under CC0 is a way to remove any legal doubt about whether researchers can use the data in their projects. Hundreds of organizations use CC0 to dedicate their work to the public domain. Although CC0 doesn’t legally require users of the data to cite the source, it does not affect the ethical norms for attribution in scientific and research communities.


## Attribution 4.0 International (CC BY 4.0)

Siehe https://creativecommons.org/licenses/by/4.0/

Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.


## Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)

Siehe https://creativecommons.org/licenses/by-sa/4.0/


Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

Das dritte ist also eine copyleft-Lizenz, wenn jemand HITO erweitert, muss er oder sie es dann auch unter der selben Lizenz verbreiten.

Das klingt erst mal gut, aber es kann sehr problematisch sein, weil verschiedene copyleft-Lizenzen inkompatibel sein können. Daher empfehle ich diese nicht zu benutzen.

Siehe auch https://opencontent.org/blog/archives/347.

Zum Beispiel benutzt Wikimedia Commons die GFDL, was auch eine freie copyleft Lizenz ist, aber man müsste dann das Ergebnis unter beiden Lizenzen veröffentlichen, was aber nicht geht.

**Comment by KonradHoeffner** [comment]
- [x] @KonradHoeffner Herausfinden, ob noch andere Dinge verboten sind. Was sagt SNOMED darüber, wenn ich die Daten doch kopieren darf. Deutschlandweite SNOMED Lizenz. Matthias Löbe fragen. Dürfen wir die Daten jemandem zeigen?
- [x] @KonradHoeffner In README schreiben, dass die SNOMED-Daten nicht weiter kopiert werden dürfen und von SNOMED lizensiert sind.

**Comment by KonradHoeffner** [comment]
Antwort von Matthias:

> 
> Es ist nicht verboten, irgendwelche Codes aus dem Browser herauszukopieren und in irgendeine Art System oder Dokument einzubauen. Du darfst sie nur nicht publizieren, d.h. öffentlich verfügbar machen. Irgendwelche Warnungen in READMEs sind irrelevant bzw. ähnlich legal wie kino.to.
> 
> Deutschland hat eine Nationallizenz, was das Recht beinhaltet, Dritten Sublizenzen auszustellen. Das heißt nicht, dass man SNOMED CT völlig frei verwenden darf, sondern nur, dass man eine Lizenz bekommen kann. Das können wir gern mal zusammen durchspielen, es gibt ein Websystem dafür und du bist dann berichtspflichtig.

Da wir für genau dieses Publizieren in HITO ja anscheinend eine Erlaubnis haben gehe ich davon aus, dass damit alles erledigt ist, wenn jemand anderer Meinung ist bitte die Issue wieder öffnen.

**Comment by AlfredWinter** [comment]
Verstehe ich nicht, da wir doch das Kopierverbot explizit gelesen haben. 
AW
 
Von: Konrad Höffner ***@***.***> 
Gesendet: Mittwoch, 19. Januar 2022 13:22
An: hitontology/ontology ***@***.***>
Cc: AlfredWinter ***@***.***>; Mention ***@***.***>
Betreff: [Extern] Re: [hitontology/ontology] Lizenz license für die Ontologie? (#82)
 
Antwort von Matthias:
Es ist nicht verboten, irgendwelche Codes aus dem Browser herauszukopieren und in irgendeine Art System oder Dokument einzubauen. Du darfst sie nur nicht publizieren, d.h. öffentlich verfügbar machen. Irgendwelche Warnungen in READMEs sind irrelevant bzw. ähnlich legal wie kino.to.
Deutschland hat eine Nationallizenz, was das Recht beinhaltet, Dritten Sublizenzen auszustellen. Das heißt nicht, dass man SNOMED CT völlig frei verwenden darf, sondern nur, dass man eine Lizenz bekommen kann. Das können wir gern mal zusammen durchspielen, es gibt ein Websystem dafür und du bist dann berichtspflichtig.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
