### ISSUE TITLE
Fehlende Anwendungssystemtypen hinzufügen

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#87]
Es gibt nur 10 Softwareprodukte mit Anwendungssystem, vielleicht  sind die restlichen in der Datenbank?

```SPARQL
SELECT COUNT(DISTINCT(?swp))
{
 ?swp hito:applicationSystem/hito:applicationSystemClassified ?as.
}
```

10

**Comment by KonradHoeffner** [comment]
```sql
SELECT COUNT(DISTINCT(swp_suffix))
FROM citation
WHERE type='ApplicationSystem'
```

40

**Comment by KonradHoeffner** [comment]
- [x] Datenbank neu importieren

Es sind aber immer noch nur 10, investigate.

**Comment by KonradHoeffner** [comment]
Citations gibt es viele:

```
SELECT COUNT(DISTINCT(?swp))
{
 ?swp hito:applicationSystem ?as.
}
```
41

Aber fast alle haben keine Classifieds:

```
SELECT COUNT(DISTINCT(?swp))
{
 ?swp hito:applicationSystem ?as.
 MINUS {?as hito:applicationSystemClassified ?asc.}
}
```
35

**Comment by MichelleBindel** [comment]
Bei einem Großteil der Software Produkte habe ich die Classifieds nachgetragen. Bei den Commercial Product Dummys habe ich eine Citation hinzugefügt die den Typ aus dem Dummy-Namen der Software wiedergibt (Bsp. "Commercial RIS2").

Produkte bei denen keine AppSysCitation vorliegen sind die aus den Studien. Da müsste man noch einmal direkt in die Studien schauen oder man geht davon aus, dass die Information nicht vorlag:

- Abbott i-Stat | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Agfa PACS IMPAX | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Agfa RIS Elefante | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Cerner First Net | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Cerner Millenium Power Orders | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Cerner Soarian CPOE platform | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- CSC Med Chart | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- e Chasqui | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- e Doc | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Eclipsys Continuum 2000 CDS | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- GE Patchspecd PACS | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- HNA Millenium | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Medicator | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Metavision | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- PIK | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- SAP R3 Business Process Control System software | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Sysmex XS 1000i haematology analyser | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Tele DICOM | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- Theriak | Softwareprodukt aus Studie, keine weiteren Infos vorhanden

Drei Produkte haben zwar Citations, aber in den integrierten Katalogen gibts es keine passenden Kategorien die zugeordnet werden können:

- 3LGM2 Baukasten | kein passender Katalogeintrag für Citation "Modell-Baukasten"
- Open-eObs | kein passender Katalogeintrag für Citation "Electronic Patient Observation System"
- OpenDental | kein passender Katalogeintrag für Citation "Dental Practice Management Software"

**Comment by KonradHoeffner** [comment]
Danke!

**Comment by MichelleBindel** [comment]
Citation finden und mit Classified hinzufügen:

- [x] Abbott i-Stat | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] Agfa PACS IMPAX | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] Agfa RIS Elefante | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [ ] Cerner First Net | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] Cerner Millenium Power Orders | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] Cerner Soarian CPOE platform | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [ ] CSC Med Chart | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] e Chasqui | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] e Doc | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] Eclipsys Continuum 2000 CDS | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] GE Patchspecd PACS | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] HNA Millenium | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [ ] Medicator | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] Metavision | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] PIK | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] SAP R3 Business Process Control System software | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [x] Sysmex XS 1000i haematology analyser | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [ ] Tele DICOM | Softwareprodukt aus Studie, keine weiteren Infos vorhanden
- [ ] Theriak | Softwareprodukt aus Studie, keine weiteren Infos vorhanden

**Comment by MichelleBindel** [comment]
@KonradHoeffner Bin die Liste oben durchgegangen, leider konnte ich nicht für alle etwas finden. Wenn dir noch etwas zum nachtragen auffällt, gib Bescheid! :-) 

Übrige Software Produkte ohne Classified:
- 3LGM2 Baukasten | kein passender Katalogeintrag für Citation "Modell-Baukasten"
- Cerner First Net | kein passender Katalogeintrag für Citation "Emergency Medicine Information System"
- CSC Med Chart | kein passender Katalogeintrag für Citation "Medication Management System"
- Open-eObs | kein passender Katalogeintrag für Citation "Electronic Patient Observation System"
- OpenDental | kein passender Katalogeintrag für Citation "Dental Practice Management Software"

Ohne AppSys Citation/Classified. Kann auch nicht hinzugefügt werden weil Softwaresystem online nicht auffindbar:
- Medicator 
- Tele DICOM
- Theriak

**Comment by KonradHoeffner** [comment]
Perfekt, vielen Dank!
