### ISSUE TITLE
FreeMedForms gelöscht?

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#88]
@MichelleBindel: Nach Neuimport aus der Datenbank gibt es FreeMedForms nicht mehr, ist das gewollt?

**Comment by KonradHoeffner** [comment]
Außerdem fehlen die direct features und functions von Orthanc, ist das auch so geplant?

**Comment by KonradHoeffner** [comment]
Habe beides erstmal noch drin gelassen im Repository in `swp.ttl` bis das geklärt ist.

**Comment by MichelleBindel** [comment]
FreeMedForms haben wir wieder gelöscht, weil sich herausgestellt hat, dass Website und Handbuch komplett auf Französich sind und wir so nicht an genug Functions/Features für die Software kommen:
https://www.freemedforms.com/fr/start

Wegen Orthanc muss ich auch erst nochmal nachschauen.
