### ISSUE TITLE
Underdescribed products

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#89]
Of the 52 software products, only 45 have at least one feature or function and only 25 have a sum of at least 10 features and functions. To get useful data out of approaches like clustering, there should be at least 10 features+functions for each product.
Add the missing ones to the 27 that don't have it.

**Comment by FranziskaJahn** [comment]
Das ist leichter gesagt als getan. Das, was jetzt in der Ontologie drinsteckt, wurde nach bestem Wissen und Gewissen aus der verfügbaren Dokumentation für die Softwareprodukte extrahiert. Es ist nicht davon auszugehen, dass da mehr zu holen ist. Es gäbe nur eine Möglichkeit, noch mehr Aufgaben und Features herauszufinden: die Softwareprodukte einzeln zu installieren und auszuprobieren. Das bekommen wir aber im Rahmen des Projekts nicht hin, da schon die Installation vieler FLOSS nicht trivial ist. 
Einige Softwareprodukte haben auch ganz einfach einen sehr eng begrenzten Funktionsumfang, z. B. DICOM Viewer. Da wäre es gar nicht sinnvoll, mehr als 10 Features und/oder Functions anzuführen.
Da müssen wir wahrscheinlich im nächsten HITO-Meeting noch mal drüber reden.
