### ISSUE TITLE
30 Produkte ohne Lizenz

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#92]
Von 52 haben nur 22 eine Lizenz.
Wenn man es nicht genau herausfindet, wenigstens die Oberklasse "Open source software licence" nehmen:
 http://www.ebi.ac.uk/swo/license/SWO_1000008

**Comment by KonradHoeffner** [comment]
http://www.ebi.ac.uk/swo/license/SWO_1000002 proprietary commercial license

**Comment by MichelleBindel** [comment]
3LGM hat noch keine Lizenz, bitte ergänzen sobald diese feststeht.

@KonradHoeffner Alle anderen wurden ergänzt, bitte von database frontend rüberziehen.

**Comment by KonradHoeffner** [comment]
Export. Dann testen mit
```
SELECT ?x
{
 ?x a hito:SoftwareProduct.
 MINUS {?x hito:license ?y.}
}
```

> http://hitontology.eu/ontology/3LGM2Baukasten

Checks out!
