### ISSUE TITLE
Katalogeinträge verlinken limes

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#94]
Damit wir die Softwareprodukte gut vergleichen können, brauchen wir eine Verlinkung der Kataloge untereinander auf Basis der classifieds.

**Comment by KonradHoeffner** [comment]
Auch bei der Faceted Search berücksichtigen. Wenn Benutzer ein classified auswählt.

**Comment by KonradHoeffner** [comment]
## Erster Versuch
Siehe https://github.com/dice-group/LIMES/issues/255.
Momentan verwende ich die Option, alle matches mit exakt 1.0 wegzuwerfen.

```
<http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryReidentificationEvent>   <http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryDeidentificationEvent>   0.8913043478260869
<http://hitontology.eu/ontology/WhoDhiUntargetedClientCommunication>    <http://hitontology.eu/ontology/WhoDhiTargetedClientCommunication>  0.8285714285714286
<http://hitontology.eu/ontology/WhoDhiTargetedClientCommunication>  <http://hitontology.eu/ontology/WhoDhiUntargetedClientCommunication>    0.8285714285714286
<http://hitontology.eu/ontology/EhrSfmDeidentifyRecordEntries>  <http://hitontology.eu/ontology/EhrSfmReidentifyRecordEntries>  0.8214285714285714
<http://hitontology.eu/ontology/EhrSfmReidentifyRecordEntries>  <http://hitontology.eu/ontology/EhrSfmDeidentifyRecordEntries>  0.8214285714285714
<http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryLinkEvent>   <http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryUnlinkEvent> 0.8461538461538461
<http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryDeidentificationEvent>   <http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryReidentificationEvent>   0.8913043478260869
<http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryLegalHoldEvent>  <http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryLegalHoldRemovalEvent>   0.851063829787234
<http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryLegalHoldRemovalEvent>   <http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryLegalHoldEvent>  0.851063829787234
<http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryMergeEvent>  <http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryUnmergeEvent>    0.85
<http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryUnmergeEvent>    <http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryMergeEvent>  0.85
<http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryUnlinkEvent> <http://hitontology.eu/ontology/EhrSfmEvidenceOfRecordEntryLinkEvent>   0.8461538461538461
``

**Comment by KonradHoeffner** [comment]
[Neue Methode](https://github.com/hitontology/ontology/commit/bbdf786ebd4fce98815137f5225c052760aa7381), Matches ohne Duplikate sind:

```
<http://hitontology.eu/ontology/WhoDhiSelfMonitoringOfHealthOrDiagnosticDataByClient>	<http://hitontology.eu/ontology/WhoDhiRemoteMonitoringOfClientHealthOrDiagnosticDataByProvider>	0.618421052631579
<http://hitontology.eu/ontology/WhoDhiNonRoutineDataCollectionAndManagement>	<http://hitontology.eu/ontology/WhoDhiRoutineHealthIndicatorDataCollectionAndManagement>	0.6129032258064516
<http://hitontology.eu/ontology/WhoDhiMapLocationOfHealthcareProviders>	<http://hitontology.eu/ontology/WhoDhiManageCertificationregistrationOfHealthcareProviders>	0.5245901639344263
<http://hitontology.eu/ontology/WhoDhiTransmitNonroutineHealthEventAlertsToHealthcareProviders>	<http://hitontology.eu/ontology/WhoDhiTransmitRoutinePayrollPaymentToHealthcareProviders>	0.5540540540540541
<http://hitontology.eu/ontology/WhoDhiTransmitOrManageIncentivesToHealthcareProviders>	<http://hitontology.eu/ontology/WhoDhiTransmitOrManageIncentivesToClientsForHealthServices>	0.52
```

**Comment by KonradHoeffner** [comment]
@FranziskaJahn: Tabellen von @MichelleBindel durchgehen und @KonradHoeffner freigeben.

**Comment by AlfredWinter** [comment]
Nicht die Kataloge verlinken, sondern die Katalogeinträge!

**Comment by KonradHoeffner** [comment]
## Citation zu Classified

Einschließlich existierender Links und ohne Berücksichtigung von gleichem Typ.

Citation | Classified | Score
| --     |  --        | --
[EChasquiLaboratoryInformationSystem](http://hitontology.eu/ontology/EChasquiLaboratoryInformationSystem) | [BbLaboratoryInformationSystem](http://hitontology.eu/ontology/BbLaboratoryInformationSystem) | 1.0
[schedulingAndResourceAllocation](http://hitontology.eu/ontology/schedulingAndResourceAllocation) | [BbSchedulingAndResourceAllocation](http://hitontology.eu/ontology/BbSchedulingAndResourceAllocation) | 1.0
[MetavisionAppClinicalInformationSystem](http://hitontology.eu/ontology/MetavisionAppClinicalInformationSystem) | [BbClinicalInformationSystem](http://hitontology.eu/ontology/BbClinicalInformationSystem) | 1.0
[laboratoryInformationSystem](http://hitontology.eu/ontology/laboratoryInformationSystem) | [BbLaboratoryInformationSystem](http://hitontology.eu/ontology/BbLaboratoryInformationSystem) | 1.0
[Cis2FuncPatientAdministration](http://hitontology.eu/ontology/Cis2FuncPatientAdministration) | [BbPatientAdministration](http://hitontology.eu/ontology/BbPatientAdministration) | 1.0
[operationManagementSystem](http://hitontology.eu/ontology/operationManagementSystem) | [BbOperationManagementSystem](http://hitontology.eu/ontology/BbOperationManagementSystem) | 1.0
[GnuHealthFuncFinancialAccounting](http://hitontology.eu/ontology/GnuHealthFuncFinancialAccounting) | [BbFinancialAccounting](http://hitontology.eu/ontology/BbFinancialAccounting) | 1.0
[GnuHealthOrgHospitalEnvironmentSctid22232009](http://hitontology.eu/ontology/GnuHealthOrgHospitalEnvironmentSctid22232009) | [SnomedHospitalEnvironment](http://hitontology.eu/ontology/SnomedHospitalEnvironment) | 1.0
[GnuHealthFuncHospitalManagement](http://hitontology.eu/ontology/GnuHealthFuncHospitalManagement) | [BbHospitalManagement](http://hitontology.eu/ontology/BbHospitalManagement) | 1.0
[Cis1FuncControlling](http://hitontology.eu/ontology/Cis1FuncControlling) | [BbControlling](http://hitontology.eu/ontology/BbControlling) | 1.0
[Dhis2AppGeographicInformationSystemGis](http://hitontology.eu/ontology/Dhis2AppGeographicInformationSystemGis) | [WhoDhiGeographicInformationSystemGis](http://hitontology.eu/ontology/WhoDhiGeographicInformationSystemGis) | 1.0
[3LGM2FuncInformationManagement](http://hitontology.eu/ontology/3LGM2FuncInformationManagement) | [BbInformationManagement](http://hitontology.eu/ontology/BbInformationManagement) | 1.0
[GnuHealthOrgHealthCenterEnvironmentSctid264361005](http://hitontology.eu/ontology/GnuHealthOrgHealthCenterEnvironmentSctid264361005) | [SnomedHealthCenterEnvironment](http://hitontology.eu/ontology/SnomedHealthCenterEnvironment) | 1.0
[patientAdministration](http://hitontology.eu/ontology/patientAdministration) | [BbPatientAdministration](http://hitontology.eu/ontology/BbPatientAdministration) | 1.0
[OpenElisFeatIndividualOrderEntry](http://hitontology.eu/ontology/OpenElisFeatIndividualOrderEntry) | [BbOrderEntry](http://hitontology.eu/ontology/BbOrderEntry) | 1.0
[measurementAnalysisResearchAndReports](http://hitontology.eu/ontology/measurementAnalysisResearchAndReports) | [EhrSfmMeasurementAnalysisResearchAndReports](http://hitontology.eu/ontology/EhrSfmMeasurementAnalysisResearchAndReports) | 1.0
[OpenMrsFuncPatientCare](http://hitontology.eu/ontology/OpenMrsFuncPatientCare) | [BbPatientCare](http://hitontology.eu/ontology/BbPatientCare) | 1.0
[OpenMrsFuncInformationManagement](http://hitontology.eu/ontology/OpenMrsFuncInformationManagement) | [BbInformationManagement](http://hitontology.eu/ontology/BbInformationManagement) | 1.0
[Dhis2FuncAppointmentScheduling](http://hitontology.eu/ontology/Dhis2FuncAppointmentScheduling) | [BbAppointmentScheduling](http://hitontology.eu/ontology/BbAppointmentScheduling) | 1.0
[Dhis2AppHmis](http://hitontology.eu/ontology/Dhis2AppHmis) | [WhoDhiHealthManagementInformationSystemHmis](http://hitontology.eu/ontology/WhoDhiHealthManagementInformationSystemHmis) | 1.0
[OrthancOrgHospitalEnvironment](http://hitontology.eu/ontology/OrthancOrgHospitalEnvironment) | [SnomedHospitalEnvironment](http://hitontology.eu/ontology/SnomedHospitalEnvironment) | 1.0
[pictureArchivalAndCommunicationSystem](http://hitontology.eu/ontology/pictureArchivalAndCommunicationSystem) | [BbPictureArchivingAndCommunicationSystem](http://hitontology.eu/ontology/BbPictureArchivingAndCommunicationSystem) | 0.8125
[electronicPatientRecordSystemEPR](http://hitontology.eu/ontology/electronicPatientRecordSystemEPR) | [BbElectronicPatientRecordSystem](http://hitontology.eu/ontology/BbElectronicPatientRecordSystem) | 0.8461538461538461
[patientDataManagementSystemPDMS](http://hitontology.eu/ontology/patientDataManagementSystemPDMS) | [BbPatientDataManagementSystem](http://hitontology.eu/ontology/BbPatientDataManagementSystem) | 0.8055555555555556
[GnuHealthAppElectronicMedicalRecordEmr](http://hitontology.eu/ontology/GnuHealthAppElectronicMedicalRecordEmr) | [WhoDhiElectronicMedicalRecord](http://hitontology.eu/ontology/WhoDhiElectronicMedicalRecord) | 0.8125
[OpenDentalFuncTreatmentAdministration](http://hitontology.eu/ontology/OpenDentalFuncTreatmentAdministration) | [EhrSfmSupportTreatmentAdministration](http://hitontology.eu/ontology/EhrSfmSupportTreatmentAdministration) | 0.7142857142857143
[OpenDentalFuncTreatmentAdministration](http://hitontology.eu/ontology/OpenDentalFuncTreatmentAdministration) | [EhrSfmManageTreatmentAdministration](http://hitontology.eu/ontology/EhrSfmManageTreatmentAdministration) | 0.7352941176470589
[Cis2FuncPatientAdministration](http://hitontology.eu/ontology/Cis2FuncPatientAdministration) | [BbPatientAdministrationSystem](http://hitontology.eu/ontology/BbPatientAdministrationSystem) | 0.7096774193548387
[OpenElisAppLaboratoryInformationSystem](http://hitontology.eu/ontology/OpenElisAppLaboratoryInformationSystem) | [BbLaboratoryInformationSystem](http://hitontology.eu/ontology/BbLaboratoryInformationSystem) | 0.8333333333333334
[Dhis2FeatWebBasedGeographicInformationSystem](http://hitontology.eu/ontology/Dhis2FeatWebBasedGeographicInformationSystem) | [WhoDhiGeographicInformationSystemGis](http://hitontology.eu/ontology/WhoDhiGeographicInformationSystemGis) | 0.7555555555555555
[patientAdministrationSystemPAS](http://hitontology.eu/ontology/patientAdministrationSystemPAS) | [BbPatientAdministrationSystem](http://hitontology.eu/ontology/BbPatientAdministrationSystem) | 0.8529411764705882
[OrthancOrgRadiologyDepartmentSctid309964003](http://hitontology.eu/ontology/OrthancOrgRadiologyDepartmentSctid309964003) | [SnomedRadiologyDepartmentEnvironment](http://hitontology.eu/ontology/SnomedRadiologyDepartmentEnvironment) | 0.7096774193548387
[enterpriseWideResourcePlanningSystemERP](http://hitontology.eu/ontology/enterpriseWideResourcePlanningSystemERP) | [BbEnterpriseResourcePlanningSystem](http://hitontology.eu/ontology/BbEnterpriseResourcePlanningSystem) | 0.782608695652174
[patientAdministration](http://hitontology.eu/ontology/patientAdministration) | [BbPatientAdministrationSystem](http://hitontology.eu/ontology/BbPatientAdministrationSystem) | 0.7096774193548387
[OpenEmrFuncPatientDemographics](http://hitontology.eu/ontology/OpenEmrFuncPatientDemographics) | [EhrSfmManagePatientDemographics](http://hitontology.eu/ontology/EhrSfmManagePatientDemographics) | 0.7
[OpenClinicGaFuncHumanResourceManagementModule](http://hitontology.eu/ontology/OpenClinicGaFuncHumanResourceManagementModule) | [WhoDhiHumanResourceManagement](http://hitontology.eu/ontology/WhoDhiHumanResourceManagement) | 0.7352941176470589
[OpenClinicGaFuncHumanResourceManagementModule](http://hitontology.eu/ontology/OpenClinicGaFuncHumanResourceManagementModule) | [BbHumanResourceManagement](http://hitontology.eu/ontology/BbHumanResourceManagement) | 0.7352941176470589
[Cis1FuncKnowledgeManagement](http://hitontology.eu/ontology/Cis1FuncKnowledgeManagement) | [WhoDhiKnowledgeManagementSystem](http://hitontology.eu/ontology/WhoDhiKnowledgeManagementSystem) | 0.7
[OpenMaximsAppPas](http://hitontology.eu/ontology/OpenMaximsAppPas) | [BbPatientAdministrationSystem](http://hitontology.eu/ontology/BbPatientAdministrationSystem) | 0.8529411764705882
[AgfaRisElefanteAppRis](http://hitontology.eu/ontology/AgfaRisElefanteAppRis) | [BbRadiologyInformationSystem](http://hitontology.eu/ontology/BbRadiologyInformationSystem) | 0.8285714285714286
[OscarEmrAppEmr](http://hitontology.eu/ontology/OscarEmrAppEmr) | [WhoDhiElectronicMedicalRecord](http://hitontology.eu/ontology/WhoDhiElectronicMedicalRecord) | 0.8125
[Cis2FeatSupportOfClinicalDocumentation](http://hitontology.eu/ontology/Cis2FeatSupportOfClinicalDocumentation) | [EhrSfmSupportClinicalDocumentation](http://hitontology.eu/ontology/EhrSfmSupportClinicalDocumentation) | 0.8611111111111112
[OpenEmrFuncElectronicMedicalRecords](http://hitontology.eu/ontology/OpenEmrFuncElectronicMedicalRecords) | [WhoDhiElectronicMedicalRecord](http://hitontology.eu/ontology/WhoDhiElectronicMedicalRecord) | 0.8333333333333334
[AgfaPacsImpaxAppPacs](http://hitontology.eu/ontology/AgfaPacsImpaxAppPacs) | [BbPictureArchivingAndCommunicationSystem](http://hitontology.eu/ontology/BbPictureArchivingAndCommunicationSystem) | 0.86
[HospitalRunUserPatientAdministrator](http://hitontology.eu/ontology/HospitalRunUserPatientAdministrator) | [BbPatientAdministration](http://hitontology.eu/ontology/BbPatientAdministration) | 0.7037037037037037
[3LGM2FuncstrategicInformationManagementPlanning](http://hitontology.eu/ontology/3LGM2FuncstrategicInformationManagementPlanning) | [BbStrategicInformationManagement](http://hitontology.eu/ontology/BbStrategicInformationManagement) | 0.75
[Pacs2FeatDICOMStructuredReporting](http://hitontology.eu/ontology/Pacs2FeatDICOMStructuredReporting) | [JoshiPacsStructuredReporting](http://hitontology.eu/ontology/JoshiPacsStructuredReporting) | 0.7
[electronicMedicalRecordSystem](http://hitontology.eu/ontology/electronicMedicalRecordSystem) | [WhoDhiElectronicMedicalRecord](http://hitontology.eu/ontology/WhoDhiElectronicMedicalRecord) | 0.7428571428571429
[GnuHealthOrgGeneralPractitionerPracticeSiteEnvironmentSctid394761003](http://hitontology.eu/ontology/GnuHealthOrgGeneralPractitionerPracticeSiteEnvironmentSctid394761003) | [SnomedGeneralPractitionerPracticeSiteEnvironment](http://hitontology.eu/ontology/SnomedGeneralPractitionerPracticeSiteEnvironment) | 0.8863636363636364

**Comment by KonradHoeffner** [comment]
## Citation zu Classified mit gleichem Typ
19 exakt gleich, 19 ab score 0,7.

Citation | Classified | Score
|   ---    |     ---     | ---
[EChasquiLaboratoryInformationSystem](http://hitontology.eu/ontology/EChasquiLaboratoryInformationSystem) |    [BbLaboratoryInformationSystem](http://hitontology.eu/ontology/BbLaboratoryInformationSystem) |  1.0
[schedulingAndResourceAllocation](http://hitontology.eu/ontology/schedulingAndResourceAllocation) |    [BbSchedulingAndResourceAllocation](http://hitontology.eu/ontology/BbSchedulingAndResourceAllocation) |  1.0
[MetavisionAppClinicalInformationSystem](http://hitontology.eu/ontology/MetavisionAppClinicalInformationSystem) | [BbClinicalInformationSystem](http://hitontology.eu/ontology/BbClinicalInformationSystem) |    1.0
[laboratoryInformationSystem](http://hitontology.eu/ontology/laboratoryInformationSystem) |    [BbLaboratoryInformationSystem](http://hitontology.eu/ontology/BbLaboratoryInformationSystem) |  1.0
[Cis2FuncPatientAdministration](http://hitontology.eu/ontology/Cis2FuncPatientAdministration) |  [BbPatientAdministration](http://hitontology.eu/ontology/BbPatientAdministration) |    1.0
[operationManagementSystem](http://hitontology.eu/ontology/operationManagementSystem) |  [BbOperationManagementSystem](http://hitontology.eu/ontology/BbOperationManagementSystem) |    1.0
[GnuHealthFuncFinancialAccounting](http://hitontology.eu/ontology/GnuHealthFuncFinancialAccounting) |   [BbFinancialAccounting](http://hitontology.eu/ontology/BbFinancialAccounting) |  1.0
[GnuHealthOrgHospitalEnvironmentSctid22232009](http://hitontology.eu/ontology/GnuHealthOrgHospitalEnvironmentSctid22232009) |   [SnomedHospitalEnvironment](http://hitontology.eu/ontology/SnomedHospitalEnvironment) |  1.0
[GnuHealthFuncHospitalManagement](http://hitontology.eu/ontology/GnuHealthFuncHospitalManagement) |    [BbHospitalManagement](http://hitontology.eu/ontology/BbHospitalManagement) |   1.0
[Cis1FuncControlling](http://hitontology.eu/ontology/Cis1FuncControlling) |    [BbControlling](http://hitontology.eu/ontology/BbControlling) |  1.0
[Dhis2AppGeographicInformationSystemGis](http://hitontology.eu/ontology/Dhis2AppGeographicInformationSystemGis) | [WhoDhiGeographicInformationSystemGis](http://hitontology.eu/ontology/WhoDhiGeographicInformationSystemGis) |   1.0
[3LGM2FuncInformationManagement](http://hitontology.eu/ontology/3LGM2FuncInformationManagement) | [BbInformationManagement](http://hitontology.eu/ontology/BbInformationManagement) |    1.0
[GnuHealthOrgHealthCenterEnvironmentSctid264361005](http://hitontology.eu/ontology/GnuHealthOrgHealthCenterEnvironmentSctid264361005) |  [SnomedHealthCenterEnvironment](http://hitontology.eu/ontology/SnomedHealthCenterEnvironment) |  1.0
[patientAdministration](http://hitontology.eu/ontology/patientAdministration) |  [BbPatientAdministration](http://hitontology.eu/ontology/BbPatientAdministration) |    1.0
[OpenElisFeatIndividualOrderEntry](http://hitontology.eu/ontology/OpenElisFeatIndividualOrderEntry) |   [BbOrderEntry](http://hitontology.eu/ontology/BbOrderEntry) |   1.0
[measurementAnalysisResearchAndReports](http://hitontology.eu/ontology/measurementAnalysisResearchAndReports) |  [EhrSfmMeasurementAnalysisResearchAndReports](http://hitontology.eu/ontology/EhrSfmMeasurementAnalysisResearchAndReports) |    1.0
[OpenMrsFuncPatientCare](http://hitontology.eu/ontology/OpenMrsFuncPatientCare) | [BbPatientCare](http://hitontology.eu/ontology/BbPatientCare) |  1.0
[OpenMrsFuncInformationManagement](http://hitontology.eu/ontology/OpenMrsFuncInformationManagement) |   [BbInformationManagement](http://hitontology.eu/ontology/BbInformationManagement) |    1.0
[Dhis2FuncAppointmentScheduling](http://hitontology.eu/ontology/Dhis2FuncAppointmentScheduling) | [BbAppointmentScheduling](http://hitontology.eu/ontology/BbAppointmentScheduling) |    1.0
[Dhis2AppHmis](http://hitontology.eu/ontology/Dhis2AppHmis) |   [WhoDhiHealthManagementInformationSystemHmis](http://hitontology.eu/ontology/WhoDhiHealthManagementInformationSystemHmis) |    1.0
[OrthancOrgHospitalEnvironment](http://hitontology.eu/ontology/OrthancOrgHospitalEnvironment) |  [SnomedHospitalEnvironment](http://hitontology.eu/ontology/SnomedHospitalEnvironment) |  1.0
[GnuHealthOrgGeneralPractitionerPracticeSiteEnvironmentSctid394761003](http://hitontology.eu/ontology/GnuHealthOrgGeneralPractitionerPracticeSiteEnvironmentSctid394761003) |	[SnomedGeneralPractitionerPracticeSiteEnvironment](http://hitontology.eu/ontology/SnomedGeneralPractitionerPracticeSiteEnvironment)	| 0.8863636363636364
[Cis2FeatSupportOfClinicalDocumentation](http://hitontology.eu/ontology/Cis2FeatSupportOfClinicalDocumentation) |	[EhrSfmSupportClinicalDocumentation](http://hitontology.eu/ontology/EhrSfmSupportClinicalDocumentation)	| 0.8611111111111112
[AgfaPacsImpaxAppPacs](http://hitontology.eu/ontology/AgfaPacsImpaxAppPacs) |	[BbPictureArchivingAndCommunicationSystem](http://hitontology.eu/ontology/BbPictureArchivingAndCommunicationSystem)	| 0.86
[patientAdministrationSystemPAS](http://hitontology.eu/ontology/patientAdministrationSystemPAS) |	[BbPatientAdministrationSystem](http://hitontology.eu/ontology/BbPatientAdministrationSystem)	| 0.8529411764705882
[OpenMaximsAppPas](http://hitontology.eu/ontology/OpenMaximsAppPas) |	[BbPatientAdministrationSystem](http://hitontology.eu/ontology/BbPatientAdministrationSystem)	| 0.8529411764705882
[electronicPatientRecordSystemEPR](http://hitontology.eu/ontology/electronicPatientRecordSystemEPR) |	[BbElectronicPatientRecordSystem](http://hitontology.eu/ontology/BbElectronicPatientRecordSystem)	| 0.8461538461538461
[OpenEmrFuncElectronicMedicalRecords](http://hitontology.eu/ontology/OpenEmrFuncElectronicMedicalRecords) |	[WhoDhiElectronicMedicalRecord](http://hitontology.eu/ontology/WhoDhiElectronicMedicalRecord)	| 0.8333333333333334
[OpenElisAppLaboratoryInformationSystem](http://hitontology.eu/ontology/OpenElisAppLaboratoryInformationSystem) |	[BbLaboratoryInformationSystem](http://hitontology.eu/ontology/BbLaboratoryInformationSystem)	| 0.8333333333333334
[AgfaRisElefanteAppRis](http://hitontology.eu/ontology/AgfaRisElefanteAppRis) |	[BbRadiologyInformationSystem](http://hitontology.eu/ontology/BbRadiologyInformationSystem)	| 0.8285714285714286
[pictureArchivalAndCommunicationSystem](http://hitontology.eu/ontology/pictureArchivalAndCommunicationSystem) |	[BbPictureArchivingAndCommunicationSystem](http://hitontology.eu/ontology/BbPictureArchivingAndCommunicationSystem)	| 0.8125
[OscarEmrAppEmr](http://hitontology.eu/ontology/OscarEmrAppEmr) |	[WhoDhiElectronicMedicalRecord](http://hitontology.eu/ontology/WhoDhiElectronicMedicalRecord)	| 0.8125
[GnuHealthAppElectronicMedicalRecordEmr](http://hitontology.eu/ontology/GnuHealthAppElectronicMedicalRecordEmr) |	[WhoDhiElectronicMedicalRecord](http://hitontology.eu/ontology/WhoDhiElectronicMedicalRecord)	| 0.8125
[patientDataManagementSystemPDMS](http://hitontology.eu/ontology/patientDataManagementSystemPDMS) |	[BbPatientDataManagementSystem](http://hitontology.eu/ontology/BbPatientDataManagementSystem)	| 0.8055555555555556
[enterpriseWideResourcePlanningSystemERP](http://hitontology.eu/ontology/enterpriseWideResourcePlanningSystemERP) |	[BbEnterpriseResourcePlanningSystem](http://hitontology.eu/ontology/BbEnterpriseResourcePlanningSystem)	| 0.782608695652174
[Dhis2FeatWebBasedGeographicInformationSystem](http://hitontology.eu/ontology/Dhis2FeatWebBasedGeographicInformationSystem) |	[WhoDhiGeographicInformationSystemGis](http://hitontology.eu/ontology/WhoDhiGeographicInformationSystemGis)	| 0.7555555555555555
[3LGM2FuncstrategicInformationManagementPlanning](http://hitontology.eu/ontology/3LGM2FuncstrategicInformationManagementPlanning) |	[BbStrategicInformationManagement](http://hitontology.eu/ontology/BbStrategicInformationManagement)	| 0.75
[electronicMedicalRecordSystem](http://hitontology.eu/ontology/electronicMedicalRecordSystem) |	[WhoDhiElectronicMedicalRecord](http://hitontology.eu/ontology/WhoDhiElectronicMedicalRecord)	| 0.7428571428571429
[OpenDentalFuncTreatmentAdministration](http://hitontology.eu/ontology/OpenDentalFuncTreatmentAdministration) |	[EhrSfmManageTreatmentAdministration](http://hitontology.eu/ontology/EhrSfmManageTreatmentAdministration)	| 0.7352941176470589
[OpenClinicGaFuncHumanResourceManagementModule](http://hitontology.eu/ontology/OpenClinicGaFuncHumanResourceManagementModule) |	[WhoDhiHumanResourceManagement](http://hitontology.eu/ontology/WhoDhiHumanResourceManagement)	| 0.7352941176470589
[OpenClinicGaFuncHumanResourceManagementModule](http://hitontology.eu/ontology/OpenClinicGaFuncHumanResourceManagementModule) |	[BbHumanResourceManagement](http://hitontology.eu/ontology/BbHumanResourceManagement)	| 0.7352941176470589
[OpenDentalFuncTreatmentAdministration](http://hitontology.eu/ontology/OpenDentalFuncTreatmentAdministration) |	[EhrSfmSupportTreatmentAdministration](http://hitontology.eu/ontology/EhrSfmSupportTreatmentAdministration)	| 0.7142857142857143
[patientAdministration](http://hitontology.eu/ontology/patientAdministration) |	[BbPatientAdministrationSystem](http://hitontology.eu/ontology/BbPatientAdministrationSystem)	| 0.7096774193548387
[OrthancOrgRadiologyDepartmentSctid309964003](http://hitontology.eu/ontology/OrthancOrgRadiologyDepartmentSctid309964003) |	[SnomedRadiologyDepartmentEnvironment](http://hitontology.eu/ontology/SnomedRadiologyDepartmentEnvironment)	| 0.7096774193548387
[Cis2FuncPatientAdministration](http://hitontology.eu/ontology/Cis2FuncPatientAdministration) |	[BbPatientAdministrationSystem](http://hitontology.eu/ontology/BbPatientAdministrationSystem)	| 0.7096774193548387
[HospitalRunUserPatientAdministrator](http://hitontology.eu/ontology/HospitalRunUserPatientAdministrator) |	[BbPatientAdministration](http://hitontology.eu/ontology/BbPatientAdministration)	| 0.7037037037037037
[Pacs2FeatDICOMStructuredReporting](http://hitontology.eu/ontology/Pacs2FeatDICOMStructuredReporting) |	[JoshiPacsStructuredReporting](http://hitontology.eu/ontology/JoshiPacsStructuredReporting)	| 0.7
[OpenEmrFuncPatientDemographics](http://hitontology.eu/ontology/OpenEmrFuncPatientDemographics) |	[EhrSfmManagePatientDemographics](http://hitontology.eu/ontology/EhrSfmManagePatientDemographics)	| 0.7
[Cis1FuncKnowledgeManagement](http://hitontology.eu/ontology/Cis1FuncKnowledgeManagement) |	[WhoDhiKnowledgeManagementSystem](http://hitontology.eu/ontology/WhoDhiKnowledgeManagementSystem)	| 0.7

**Comment by KonradHoeffner** [comment]
Um das mit den existierenden zu vergleichen, habe ich das Resultat mal in einen lokalen Virtuoso geladen mit dem Prädikat hito:test und davon die existierenden abgezogen, da bleiben aber nur 3 übrig:

`SELECT * { ?citation hito:test ?classified. MINUS {?citation ?p ?classified. ?p rdfs:subPropertyOf hito:classified.}}`

<nav class="navbar navbar-expand-md sticky-top navbar-light bg-light"><a class="navbar-brand" href="http://localhost:8102/sparql?default-graph-uri=&amp;query=SELECT+*+%7B+%3Fcitation+hito%3Atest+%3Fclassified.+MINUS+%7B%3Fcitation+%3Fp+%3Fclassified.+%3Fp+rdfs%3AsubPropertyOf+hito%3Aclassified.%7D%7D&amp;format=text%2Fhtml&amp;timeout=0&amp;signal_void=on#" onclick="javascript:history.go(-1); return false;"></a></nav>


citation | classified
-- | --
http://hitontology.eu/ontology/Cis2FeatSupportOfClinicalDocumentation | http://hitontology.eu/ontology/EhrSfmSupportClinicalDocumentation
http://hitontology.eu/ontology/GnuHealthAppElectronicMedicalRecordEmr | http://hitontology.eu/ontology/WhoDhiElectronicMedicalRecord
http://hitontology.eu/ontology/electronicMedicalRecordSystem | http://hitontology.eu/ontology/WhoDhiElectronicMedicalRecord

Aber es war trotzdem gut, das mal ausprobiert zu haben.

**Comment by MichelleBindel** [comment]
Die drei übrigen sehen gut aus!

@KonradHoeffner bitte in der turtle file hinzufügen
