### ISSUE TITLE
Recherche Kompetenzen

### ISSUE THREAD

**Issue by MichelleBindel** [hitontology/ontology#98]
Use Case Kompetenzen – Idee AW in HITO-Metamodell und Ontologie aufnehmen
https://docs.google.com/document/d/1i1bkNOX6nEHe_ng9-IvKonYJ-h5avFC6/edit#
in Antrag reinschauen, plausibel machen, dass es sinnvoll ist. Evtl. anhand von Stellenanzeigen überprüfen.

- [x] Indeed Kompetenzlevel anschauen: https://www.indeed.com/career-advice/career-development/levels-of-competence - hilft anscheinend bei Konzept von AW nicht weiter
- [x] Challenges to the assessment of competence and competencies. https://psycnet.apa.org/record/2007-14485-004
- [x] Competency benchmarks: A model for understanding and measuring competence in professional psychology across training levels. https://psycnet.apa.org/record/2009-21633-004
- [x] Nationaler Kompetenzbasierter Lernzielkatalog Medizin https://nklm.de/zend/menu

Am Ende 10 Rollen beschreiben, z. B. aus Stellenanzeigen

**Comment by MichelleBindel** [comment]
Quelle Stellenangebote:
https://www.gmds.de/de/stellenangebote/

**Comment by MichelleBindel** [comment]
Kompentenzen speziell für Medizininformatiker:

- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8286765/
--> speziell Domain 2
- http://hitcomp.org/competencies/
- https://medinform.jmir.org/2020/1/e15748/?utm_source=TrendMD&utm_medium=cpc&utm_campaign=JMIR_TrendMD_1
- https://bmjopen.bmj.com/content/9/3/e025460.full

Kann ich nicht drauf zugreifen:
https://www.sciencedirect.com/science/article/abs/pii/S138650562030993X?via%3Dihub

**Comment by KonradHoeffner** [comment]
@MichelleBindel: 20 Stellenanzeigen durchgehen und Kompetenzlevel identifizieren. Kurze Stichwörter oder Sätze untereinander reicht, keine qualitative Analyse nötig.

**Comment by MichelleBindel** [comment]
Formulierungen aus ca. 40 Stellenanzeigen von https://www.gmds.de/de/stellenangebote/

Interesse an
Kenntnisse in
Kenntnisse bzw. Interesse im Bereich
Gute Kenntnisse in
Grundkenntnisse im Bereich
Gute methodische Kenntnisse in
Sehr gute Kenntnisse in
Ausgezeichnete Kenntnisse in
Fundiertes Kenntnisse in
Anwendungsbreite Kenntnisse
Umfassende Kenntnisse in
Fortgeschrittene Kenntnisse

Erfahrung mit
Experience in/with
erste Erfahrungen mit
Praxis- bzw. Projekterfahrung mit
Praktische Erfahrung
Practical experience in
Hands-on experience in
Demonstrated hands-on experience with
Hintergrundwissen bzw. Erfahrung mit
Sehr gute Erfahrung mit
Vertiefte Kenntnisse und Erfahrungen im Bereich

Skills in
Good Skills in
Gute Fähigkeiten im Bereich
ausgeprägte Fähigkeiten
Advanced Proficiency in

Knowledge of
Grundlagenwissen im Bereich
Sound knowledge of
Hintergrundwissen in
Belastbares Knowhow im Bereich
Advanced knowledge of
Pronounced Understanding of
Ausgeprägtes Verständnis von
Ausgeprägtes Fachwissen
Excellent working knowledge of

Erfahrungen im Umgang mit
sicherer Umgang im Bereich
sicherer Umgang mit
selbstverständlicher Umgang mit
Routinierter, sicherer Umgang mit

Programmiererfahrung mit
Entwicklungserfahrung mit
(Praxisorientierte) Programmierexpertise
Sehr gute Programmierkenntnisse
Hohe Programmieraffinität

Berufliche Erfahrung in 
Tätigkeiten in
Berufserfahrungen im Bereich
erste Berufserfahrung im Bereich
Nachgewiesene Berufserfahrung mit
Mindestens X Jahre einschlägige Berufserfahrung
Mehrjährige Berufs- und Führungserfahrung

**Comment by KonradHoeffner** [comment]
@FranziskaJahn fragt @BirgitSNIK, ob sich das überlappt mit HI-LONa.

Danach mit Prof. Winter besprechen und in die Ontologie einbauen.

**Comment by FranziskaJahn** [comment]
In HI-LONa wird die vielzitierte Taxonomie nach Bloom verwendet. Es gibt vier grobe Kompetenzlevels:

1.  Kennen und Verstehen
2. Anwenden und Analyiseren
3. Beurteilen und Synthese
4. Einstellungen, Werte und Handlungen.

Zu den 4 Levels gibt es noch Listen von Verben, die für die genauere Beschreibung von Kompetenzen genutzt werden können.
Wir könnten diese Verben dann noch um solche Formulierungen erweitern, die Michelle in den Stellenanzeigen gefunden hat. 
"Programmieren" würde sich z. b. auf Stufe 2 einordnen. 
Auch hat Birgit angeregt, die neue Klasse in HITO, der die Kompetenzen zugewiesen werden sollen, nicht mit "Rolle" zu benennen, da dies mehrdeutig ist. Hier wäre ein konkreterer Name besser, z. B. "Information Management Staff".

**Comment by KonradHoeffner** [comment]
Wollen wir das jetzt umsetzen wie in HI-LONa oder nicht? Im nächsten Meeting besprechen.

**Comment by KonradHoeffner** [comment]
Implementieren in https://github.com/hitontology/ontology/issues/106.
